### ISSUE TITLE
Still not sure how to edit jurisdiction.

### ISSUE THREAD

**Issue by blipblitz** [MuckRock/muckrock#1021]
Heyyo,

We got another suggestion for a jurisdiction page thing. Here it is: 

"Suggestion: add the law firm Rankin & Taylor to the list of attorneys who do NY State FOIL law -- http://drmtlaw.com/ They've handled two lawsuits for me..so far. :-)
USER
Reclaim The Records"

Let me know how to change the page myself/if you add this yourself!

**Comment by freddymartinez9** [comment]
In Illinois, people who file suits on FOIA can, to paraphrase "can potentially win attorneys fees". In fact, if you do prevail in IL, you are able to recover attorney fees. But I am unclear on the scope of the users feedback, it seems to cover two distinct cases: a) "add an option to give details to call an attorney who is knowledgeable and wiling to listen to your FOIL case" and  b) "add information about FOIL law in NY for the user".

**Comment by morisy** [comment]
Talked to Beryl, this is all set on a feature side.
