### ISSUE TITLE
Something weird with submission. 

### ISSUE THREAD

**Issue by blipblitz** [MuckRock/muckrock#1022]
For some reason, the user got a "TASK error message" when trying to submit this request to an agency with a fax number in our database. 

https://www.muckrock.com/foi/united-states-of-america-10/gitmo-detainee-library-standard-operating-procedures-27232/#tasks

It generated this task:

https://www.muckrock.com/task/snail-mail/88980/

I've resent it, but if you could check what happened, that'd be dope.

B

**Comment by morisy** [comment]
Hi @blipblitz, 

Have you run into this again? If so please re-open but I haven't heard anything about it in a while. Thanks!
