### ISSUE TITLE
Sending as resident user to proxy state (Delaware)

### ISSUE THREAD

**Issue by blipblitz** [MuckRock/muckrock#1023]
I tried to resubmit this request...

https://www.muckrock.com/foi/delaware-236/foia-policy-delaware-department-of-corrections-27019/

...but since it's to a Delaware agency without an associated proxy, it keeps getting stalled in Snail Mail. Jonathan is from Delaware, and I've set his state on his user page, so I'd like to just be able to mail things to Delaware under his name, but he shouldn't be used as the proxy for every request. 

I don't think there's an option for this or at least it's not something that's happening automatically, because I just kept generating flags trying to resubmit. At this point, I'm just going to have it mailed, but another ping point on proxies.

**Comment by morisy** [comment]
I think this is by and large resolved through other features/processes we have in place.
