### ISSUE TITLE
Difficulty finding an agency

### ISSUE THREAD

**Issue by shawnmusgrave** [MuckRock/muckrock#1037]
I submit a lot of requests to the DoD IG — agency name in our database:  [Department of Defense, Office of the Inspector General](https://www.muckrock.com/agency/united-states-of-america-10/dod-office-of-the-inspector-general-102/)

The agency used to jump to the top of the agency list when I started typing anything at all, and particularly "defense." But I just filed a [new request](https://www.muckrock.com/foi/united-states-of-america-10/dod-ig-army-commands-need-to-improve-safeguards-that-protect-siprnet-access-points-27703/), and it took typing out "department of defense" before the agency showed up as an option. Not sure whether something changed in the text predict, but I wanted to bring it up in case it means more users may accidentally submit new agency requests.

**Comment by morisy** [comment]
I think this is fixed with our recent rollout; Shawn, if you have issues please re-open and detail.
