### ISSUE TITLE
One click action to extend embargoes another 30 days

### ISSUE THREAD

**Issue by allanlasser** [MuckRock/muckrock#1060]
I am getting feedback from users, and one particular piece of feedback from longtime user J.K. Trotter was that he gets multiple emails daily telling him about an embargo is about to expire. According to him, me maintains about 100 embargoes at any one time.

One solution is to notify users about all their embargoes within 1 email update, as well as including buttons for each embargo in that email to extend the embargo by another 30 days when clicked.

**Comment by mitchelljkotler** [comment]
we have bulk updates for this now
