### ISSUE TITLE
Unclear whether New Agency contact info saved

### ISSUE THREAD

**Issue by shawnmusgrave** [MuckRock/muckrock#1076]
After submitting a request to a new agency, a Task pops up on the request page: https://www.muckrock.com/foi/boston-3/bpd-paid-detail-receivables-review-2013-29013/#tasks

I dutifully filled in contact info for the new agency and clicked "Save". 

![screen shot 2016-10-23 at 3 27 39 pm](https://cloud.githubusercontent.com/assets/7838930/19628866/d0abe258-9935-11e6-9a57-bc2cf0970354.png)

No confirmation came up, so it's unclear whether the suggested contact info has been saved or if I missed a required field.

**Comment by mitchelljkotler** [comment]
I just tried this as a non-admin user and a confirmation did indeed come up at the top of the screen in green.  Either this got fixed since the bug was filed or is there something more you are looking for?

**Comment by shawnmusgrave** [comment]
Nope, sounds resolved!
