### ISSUE TITLE
Map FOIAMachine subdomain for beta.foiamachine.org usage

### ISSUE THREAD

**Issue by morisy** [MuckRock/muckrock#1078]
If I try and get into details, I'll completely mess them up, but we need to configure beta.foiamachine.org to point to our server and properly serve up the FOIAMachine Beta. Allan, Mitch and Michael should probably discuss further.

**Comment by freddymartinez9** [comment]
if beta.foiamachine has HSTS and is forwarding to staging MR, you will throw a TLS error every time. that being said, there are ways around it, just depends on _how_ the certs are created _and_ traffic is being sent forward. I can try to help. (also I recommend an "operations" label for issues like this).

**Comment by mitchelljkotler** [comment]
@freddymartinez9 Thanks, we got this figured out.  I ended up using a multi-domain certificate to cover both the muckrock and foiamachine domains and its all working now.
