### ISSUE TITLE
Save crowdsource efforts

### ISSUE THREAD

**Issue by allanlasser** [MuckRock/muckrock#1083]
Right now we create Google Forms for each crowdsource, then embed the same form to multiple articles. It would be great if we could have a new model that wraps around a link to a Google Form, maybe with some additional metadata like a title, description, and image, to include on articles instead. Also, we could display these in other locations, like the homepage or a dedicated "Help Out" page.

**Comment by morisy** [comment]
I'm looking into Coral Ask for this

**Comment by mitchelljkotler** [comment]
Coral Ask, while maybe nicer than google forms, would still mean the data is not owned by us, and thus wouldn't really resolve the issue of us saving the data.
