### ISSUE TITLE
Activity Digests not sending: SSL Error

### ISSUE THREAD

**Issue by allanlasser** [MuckRock/muckrock#1085]
An SSL SYSCALL error is being raised when a celery worker tries to perform the `send_activity_digest` task. [Sentry](https://sentry.io/muckrock/app4858795herokucom/issues/112762408/)

I believe this is to blame for activity digests not being sent recently.

**Comment by mitchelljkotler** [comment]
https://github.com/celery/celery/issues/2772

**Comment by morisy** [comment]
Is this still an open problem?

**Comment by mitchelljkotler** [comment]
Yes, its very intermittent though
