### ISSUE TITLE
Rendering issues in Safari 5

### ISSUE THREAD

**Issue by morisy** [MuckRock/muckrock#1101]
We might just close as won't fix, but user reported rendering issues in Safari 5, which I guess is still in use for Power PC Macs? Apple still offers a download of it for Snow Leopard.

![screen shot 2016-11-26 at 9 18 44 pm](https://cloud.githubusercontent.com/assets/136939/20648073/0d4bb4ea-b46b-11e6-86ee-c4c9c8b375ec.png)

![screen shot 2016-11-26 at 9 18 21 pm](https://cloud.githubusercontent.com/assets/136939/20648074/10c31190-b46b-11e6-857e-39be91e5c83c.png)

**Comment by mitchelljkotler** [comment]
https://github.com/jonathantneal/flexibility
