### ISSUE TITLE
Remove <p> tags from articles

### ISSUE THREAD

**Issue by morisy** [MuckRock/muckrock#1109]
A markdown update rendered all old articles that were manually given <p> tags broken. Example:

https://www.muckrock.com/news/archives/2013/mar/04/fbi-investigated-whitney-houston-fan-letters/

If we just remove all \<p\> and \</p\> things should be (famous last words) fine.

**Comment by morisy** [comment]
Example:

https://www.muckrock.com/news/archives/2013/mar/04/fbi-investigated-whitney-houston-fan-letters/

I think this was changed to involve less html code for security reasons, though not sure how bad a little <p> tag could be.

**Comment by mitchelljkotler** [comment]
So in the example, I see the \<p\> tags working fine and none of the images working.  Why do you think removing the \<p\> tags will help?
