### ISSUE TITLE
MuckBot down

### ISSUE THREAD

**Issue by morisy** [MuckRock/muckrock#1110]
It looks like MuckBot stopped working on the 8th:

https://www.muckrock.com/task/response/?page=408&per_page=25&resolved_by=4012&resolved=on

Still analyzes communications, just doesn't act on them.

**Comment by mitchelljkotler** [comment]
Due to how we handle the Site configuration now with FOIA Machine - disabled Site usage for dbsettings - also dbsettings is terrible we should replace it with something else
