### ISSUE TITLE
Un-followed request won't leave "My Requests" lists (from a user)

### ISSUE THREAD

**Issue by blipblitz** [MuckRock/muckrock#1113]
MESSAGE
Do un-followed requested stay listed in "My requests" https://www.muckrock.com/foi/list/following/ ? I noticed a request that is listed in my"following" requests section and cant "unfollow" it. I clicked the unfollow button. I get the acknowledgement. ("You are no longer following this request."), but it is still listed. Not a big deal, just wondering. Thanks and have a great day.

USER
Andrew Roberts

https://www.muckrock.com/foi/united-states-of-america-10/booz-allen-hamilton-contracts-3328/

**Comment by mitchelljkotler** [comment]
So this view was actually totally broken (it didn't actually show you the requests you were following, it showed some arbitrary set of other requests).  Should be all fixed up now.
