### ISSUE TITLE
Resolve Open Response Tasks When User Changes Status

### ISSUE THREAD

**Issue by morisy** [MuckRock/muckrock#1116]
When a user changes the current status, it eliminates a lot of the value of staff resolving response tasks, particularly now that we have a few hundred thousand coded. In order to reduce wait time and staff burden, when a user changes the status on a request page, any open response tasks should be marked as resolved so that no one has to do them.

The "Status Changed by User" tasks should continue to be generated as normal.

The status of the communication should be left blank so that messy, unverified user data is not dirtying up our beautiful, pristine database.

**Comment by blipblitz** [comment]
It seems, though, that if there is, for some reason, a Snail Mail or a Flagged task waiting to be taken care of, those should not be resolved.

**Comment by morisy** [comment]
Good point, but yes, the only tasks it should resolve are response tasks.
