### ISSUE TITLE
Embargoed requests visible in Q&A

### ISSUE THREAD

**Issue by morisy** [MuckRock/muckrock#1118]
A user helpfully noted that it's possible to gain some data about embargoed requests if:

* A user publicly asks a question about it. Then the request metadata is public.
* Another user without permissions can click "clone" and often get roughly the entire request language.

I think this isn't as much a problem once  #1117 is implemented, but probably a good idea to check embargo status before displaying the related requests in general.

**Comment by Jberlinsky** [comment]
@morisy @mitchelljkotler I reported this bug, as well as #1117, via email before I realized that Muckrock had been open-sourced. I would love to take ownership of both issues, if y'all will have me :)

**Comment by mitchelljkotler** [comment]
The metadata will not be shown if the user does not have permission to see the request

If someone somehow guesses the URL (or its leaked in another way similar to this in the future), cloning a request you do not have access to will now 404 instead of revealing the request language
