### ISSUE TITLE
Question list doesn't show unanswered questions by default

### ISSUE THREAD

**Issue by mitchelljkotler** [MuckRock/muckrock#1120]
You need to click the unanswered checkbox, which then only shows unanswered questions (no way to view all)

Is this the desired behavior?

**Comment by morisy** [comment]
No. I think ideally it should show all by default, with the "unanswered" tick undone, and then if you *just* want to see unanswered you can tick it. Would also be OK with a three-way toggle but I think just the tick would be simpler/better.
