### ISSUE TITLE
Payment Snail Mails aren't resolving

### ISSUE THREAD

**Issue by blipblitz** [MuckRock/muckrock#1134]
Tried resolving the most recent snail mail task for this request and it didn't do anything. Should have resolved with appropriate status and a note with the check number/amount.

https://www.muckrock.com/foi/topeka-14871/tac-vehicles-31770/

**Comment by mitchelljkotler** [comment]
Did you close it by hand, because it looks like the status/note is correct now.

**Comment by blipblitz** [comment]
Yeah, we did.

**Comment by blipblitz** [comment]
And, actually, I can't tell how widespread this problem is. I tried overriding the resolved tasks on this request --- to change their statuses from Awaiting Response to NRD--- and nothing happened and the request status was certainly not changed. I've now changed it manually.
