### ISSUE TITLE
Modify embed Google Analytics tracking

### ISSUE THREAD

**Issue by morisy** [MuckRock/muckrock#1139]
Right now, Google Analytics on embeds is messing up and double counting page views for pages. As best I can tell, when an embed is on a page it treats the page as if the visitor then clicked through to that second page, meaning that the original page time is undercounted dramatically, in addition to inflating traffic.

Also, I don't think there's any GA code on document embeds, just project and crowdfund (double check?) embeds.

I think we should still do some analytics, but find a way to set it aside or mark it so that it's counted separately. We should discuss more pre-implementation.

**Comment by mitchelljkotler** [comment]
Doesn't look good for iframes:
http://online-behavior.com/analytics/iframes
https://moz.com/blog/how-to-rid-your-website-of-six-common-google-analytics-headaches
I'm pretty sure I was against IFrames from the start, I'm still not sure why we are using them at all

**Comment by mitchelljkotler** [comment]
To clarify, I am ok with IFrame embeds for embedding our content on other people's sites, but they don't seem appropriate for content within our own site.
