### ISSUE TITLE
Crowdfund backer display bug

### ISSUE THREAD

**Issue by morisy** [MuckRock/muckrock#1140]
So there's some kind of count bug in the crowdfund widget.

I feel like the count is just delayed? I've seen it on a few and haven't seen a pattern like previous bug. But we just had three donors (I did an anonymous one, one where I show my name, and a user did one where they asked to be listed), and while the amount has gone up, it says no backers and it lists no names:

https://www.muckrock.com/foi/massachusetts-1/marijuana-arrest-reports-30864/

Not sure what's going on, but I saw this before and I think it's a delay?

**Comment by morisy** [comment]
OK, so now it's showing up properly:

https://www.muckrock.com/crowdfund/91/

**Comment by mitchelljkotler** [comment]
https://github.com/MuckRock/muckrock/blob/master/muckrock/crowdfund/templatetags/crowdfund_tags.py#L95

The crowdfund widget is cached for 15 minutes under the assumption its ok if that data is not up to the minute correct.  I think I could easily invalidate the cache when someone donates if we need this to be more real time.

**Comment by morisy** [comment]
OK, thanks. Yeah, if we could invalidate cache after a donation that would be good. I just thought it was weird that the total donated was updated but how many people donated wasn't?

**Comment by mitchelljkotler** [comment]
Hmm, I don't remember why I'm only caching some of the data, must have been the slower DB queries.  If the cache invalidation works perfectly could try to cache more of it for as long as possible, since it will always be correctly invalidated.
