### ISSUE TITLE
Appealing to an agency outside of the jurisdiction.

### ISSUE THREAD

**Issue by blipblitz** [MuckRock/muckrock#1141]
Currently, it doesn't seem we can assign an appeal agency outside of the jurisdiction for the agency being appealed. This can cause a hiccup in states like Massachusetts, where all appeals are sent to the Secretary of Public Records.

**Comment by mitchelljkotler** [comment]
Would restricting it to its parent jurisdiction make sense?  Would there ever be an appeal agency to a different jurisdiction besides the parent?
