### ISSUE TITLE
DocumentCloud Viewer Broken on new requests

### ISSUE THREAD

**Issue by morisy** [MuckRock/muckrock#1143]
No idea what's going on, because the thumbnail is still working, but the viewer is not working on some recent requests:

https://www.muckrock.com/foi/united-states-of-america-10/steve-bannon-military-record-32692

But it is working on some older requests:

https://www.muckrock.com/foi/minneapolis-1607/mac-arrest-records-for-gregory-walter-jarrett-11837/#file-21446

I haven't looked into it much, but could possibly be an unembargo related buck OR from the switch over with #1136

**Comment by mitchelljkotler** [comment]
It looks like the document is still processing on DocumentCloud... I'm not sure why, we'll want to check in with them

**Comment by mitchelljkotler** [comment]
Just  an import error on that one document, doccloud helped to fix it
