### ISSUE TITLE
Markdown support for flatpages

### ISSUE THREAD

**Issue by morisy** [MuckRock/muckrock#1146]
I can't find this, but I could've sworn it'd been opened at some point. Having MarkDown support for flat pages (maybe optional if it breaks other flat page designs) would be great, especially if we could add a markdown variant that supports tables.

One page that needs updating once this is implemented:

https://www.muckrock.com/financial/

**Comment by mitchelljkotler** [comment]
http://pythonhosted.org/Markdown/extensions/tables.html

**Comment by mitchelljkotler** [comment]
You must set the tempalte to `flatpages/markdown.html` - this is to not break compatibility with existing flatpages which are rendered using django templating system - which seems unnecessary to me but I'm not sure how many of the current flat pages are utilizing that.
