### ISSUE TITLE
Change "Summary" field under Jurisdiction "Law" object to "Major Dates"

### ISSUE THREAD

**Issue by morisy** [MuckRock/muckrock#1148]
The summary field in the law is currently a text area, but during work on the guides it was used just to note the date the law was passed, as well as any dates of major updates.

It should be moved to just a text field instead of a text area (always one line), and the name should be changed to reflect this. Will need to make sure when it's changed that it's still called properly on state jurisdiction pages, which is the only place it's used.

**Comment by mitchelljkotler** [comment]
If this is always dates would there be any value in storing it in a more structured way?  If we store the year as a number in the database it would allow for comparing dates, etc if we ever wanted to do any analysis like that.  Or we could keep it simple and just change it to be a one line text field

**Comment by morisy** [comment]
Yeah, definitely some value, and then could be additive with year / kind of change (created, updated, replaced, etc?) / a deeper description of what that update is. 

At this point, though, I'm not exactly sure what that second category of things would include, and it seemed like a lot less data reentry to just change it to a one-line text field for now.
