### ISSUE TITLE
CC Receipts to Additional Addresses

### ISSUE THREAD

**Issue by morisy** [MuckRock/muckrock#1150]
On a user's profile page, we should allow them to carbon copy receipts to other addresses. This is something that's occasionally requested by a variety of our customers at larger organizations.

I think if we limit it to something like 5 additional CC email fields, with different emails separated by a comma or on different lines in a text, that should be fine, but there's a few ways it could be implemented. Basic key is that every time we generate a receipt, send it to both the user and whatever address(es) are in that field.

**Comment by morisy** [comment]
Once completed, take care of adding emails to account as promised here:

https://mail.google.com/mail/u/1/#inbox/15a4247159e87339

**Comment by mitchelljkotler** [comment]
Linking to gmails like that doesn't work for me

**Comment by morisy** [comment]
Just a note for myself since I don't want to include user info in github issues

**Comment by mitchelljkotler** [comment]
Is this a feature that should be on Organization's settings instead of individual user settings?

**Comment by morisy** [comment]
I don't think so, because some Pro users will want to have their receipts CC'd somewhere.
