### ISSUE TITLE
Appeal bug?

### ISSUE THREAD

**Issue by blipblitz** [MuckRock/muckrock#1153]
From Mike Best:

"Tried to send an appeal, got the notice "Your appeal has been sent. This request cannot be appealed." Probably a bug, and it looks like the appeal has posted, but figured I'd report it FWIW."

Re: this request - https://www.muckrock.com/foi/united-states-of-america-10/trump-for-america-30251/

(Here's the flag: https://www.muckrock.com/task/flagged/115663/)

**Comment by mitchelljkotler** [comment]
I imagine he must have hit submit twice...
