### ISSUE TITLE
Organization Page calls wrong data in columns

### ISSUE THREAD

**Issue by morisy** [MuckRock/muckrock#1155]
It looks like the Organization Page is calling the Org ID and Name instead of Name and Org Owner.

![screenshot 2017-02-26 13 54 21](https://cloud.githubusercontent.com/assets/136939/23342578/1905d146-fc2b-11e6-970f-9fa3aab611f5.png)

**Comment by mitchelljkotler** [comment]
This would be appropriate for `Low Hanging Fruit`
