### ISSUE TITLE
Vagrant Virtualbox File 404s

### ISSUE THREAD

**Issue by morisy** [MuckRock/muckrock#1156]
It looks like the Virtualbox link 404s:

https://vagrantcloud.com/ubuntu/boxes/wily64/versions/20160226.0.0/providers/virtualbox.box

I swapped in this link, which is a later version of ubuntu, and it is at least downloading:

https://atlas.hashicorp.com/ubuntu/boxes/trusty64/versions/20170222.0.0/providers/virtualbox.box

**Comment by mitchelljkotler** [comment]
Yeah, this was noted already in #1119 - That version of Ubuntu is no longer supported, so I guess that means they stopped hosting the Vagrant link.  We had to upgrade from the LTS version to get the version of postgresql we needed.  The solution is to upgrade versions - probably to the next LTS version.  However, I'll need to ensure the versions of everything we need is available on the new OS version and works as expected.

**Comment by jacksongs** [comment]
Hello, I'm scoping out MuckRock code for a project in Australia, and just wanted to note that I hit this 404 as well. I am proceeding with the ubuntu/trusty64 option as suggested by @morisy. I'll let you know if I come across any roadblocks. Love your work, keep it up.
