### ISSUE TITLE
Sample settings.sh with instructions on how to get API keys

### ISSUE THREAD

**Issue by morisy** [MuckRock/muckrock#1157]
If key API keys are going to saved in a file, we should have a more general settings.sh default file (settings.sh.default) that users can rename and put in their own keys so that they have a natural checklist of things to go through. This is how WordPress and Drupal installations run, with a sample file that needs to be renamed with install-specific data saved when it's renamed.

It'd also be good if that file included commented out instructions just pointing people to the URLs on where to get those API keys.

idk if related to #1111

**Comment by mitchelljkotler** [comment]
Unrelated to #1111 - that is for dynamic settings (like turning muckbot on or off, or whether to send emails on the weekends).

As for the issue itself, yes I agree.
