### ISSUE TITLE
Individual Communication Attachments Undeletable

### ISSUE THREAD

**Issue by morisy** [MuckRock/muckrock#1158]
This request:

https://www.muckrock.com/foi/united-states-of-america-10/bob-hope-leslie-townes-hope-31314/

Has too attachments that don't belong there, 1-12-17 MR30252 NRD ID#PRI-17-031.pdf and 1-12-17 MR30088 RES ID#PRI-17-023.pdf. Unfortunately, when I go into the communication page, click delete next to those two attachments, and click "Save and Edit", no errors are thrown but the attachments won't delete:

https://www.muckrock.com/admin/foia/foiacommunication/325397/change/

**Comment by mitchelljkotler** [comment]
> Has too attachments that don't belong there

How many?
