### ISSUE TITLE
Block anonymous flag submissions

### ISSUE THREAD

**Issue by morisy** [MuckRock/muckrock#1161]
So we knew this day was coming, but a logged out person submitted a ton of what I think are automated spam flags. They're all similar to:

tinfoil_5106a34e-0256-4bf2-9187-adeca0c3d246
tinfoil_18aa459a-45f4-4738-800d-29727a945b73

We've almost never gotten anything of value from logged out user flags, so for now I think we should just disable submitting, and then maybe later revisit with a captcha or some kind of anti-spam in place.

**Comment by morisy** [comment]
Just so we have an example logged:

https://www.muckrock.com/task/flagged/120277/

**Comment by morisy** [comment]
And now they're trying to inject some XSS attacks. Seems like a script kiddy since it says "XSS" in it

**Comment by mitchelljkotler** [comment]
Forgot to do agency and jurisdiction flags
