### ISSUE TITLE
R2D2 doesn't like responses from the NYC Mayor's Office

### ISSUE THREAD

**Issue by allanlasser** [MuckRock/muckrock#1168]
Hello 👋 

[I got responsive documents from the NYC Mayor's Office](https://www.muckrock.com/foi/new-york-city-17/linknyc-complaints-28278/?#comm-351880) but the request didn't complete and the files weren't added to the request, since they weren't attachments on the email. They also followed up with a notice my request was fulfilled, but that reset the status to `Awaiting Response`. I'm guessing R2D2 classified it, since a person probably would've caught this. I'd fix it myself, but Michael took away my superuser privileges 😭

**Comment by mitchelljkotler** [comment]
Can't you update the status on your own requests without superuser status?

**Comment by morisy** [comment]
You can still click "Edit Status" and set it, right? R2D2 actually got it right (proof below) but with a low enough confidence that it is still awaiting a human to actually set it.

**Comment by mitchelljkotler** [comment]
:robot:

**Comment by allanlasser** [comment]
Yeah, I forgot I could change the status myself. Nevermind, then! 😅
