### ISSUE TITLE
FOIA Machine password change page

### ISSUE THREAD

**Issue by morisy** [MuckRock/muckrock#1171]
FOIA Machine was kept very simple on purpose. One thing it doesn't have is profile pages.

That's fine for now, but at some point it would be good to add that and along with that a way to change passwords beyond the normal "reset password" tool for logged out users.

**Comment by mitchelljkotler** [comment]
They can change their password by logging in to muckrock

**Comment by mitchelljkotler** [comment]
I believe squarelet makes this obsolete... although maybe we should have a link back to squarelet
