### ISSUE TITLE
'Update' email button doesn't work 

### ISSUE THREAD

**Issue by jimmyfavourite** [MuckRock/muckrock#1174]
Doesn't seem to do anything on Chrome for me.

**Comment by mitchelljkotler** [comment]
Which page is this on?

**Comment by jimmyfavourite** [comment]
https://www.muckrock.com/accounts/settings/
'Update Email'

**Comment by mitchelljkotler** [comment]
I just tried it out and it works fine for me.  You type the new email address into the text box, click 'Update Email' and it sets your email address to what you entered.  Do you have any browser extensions that might be interfering?  JavaScript blocker, Ad blockers, or other privacy extensions sometimes cause problems.

**Comment by jimmyfavourite** [comment]
Ah yes tried it without my ad-blocker works fine. My mistake.
