### ISSUE TITLE
Messenger system 

### ISSUE THREAD

**Issue by ghost** [MuckRock/muckrock#1175]
A messenger/chat feature would good to have.

**Comment by mitchelljkotler** [comment]
Could you be a little more specific in what exactly are you looking for?  Private messages between users?  A message forum?

We also have the Q&A section which allows for discussion on specific questions about requests or records access in general and the Slack chat for real time discussion.  If you are not in the Slack room let me know and we can get you an invite.

**Comment by jimmyfavourite** [comment]
I think a forum would be great! Coupled with a chat system like Slack or Facebook would be useful too.

**Comment by morisy** [comment]
Hi! If you haven't already, register for the Slack here: https://www.muckrock.com/slack/

We have a public forum for questions here, and are trying to find ways to make it more useful: https://www.muckrock.com/questions/

I think this covers about what we have the resources to tackle now, but feel free to let us know if you've got more ideas!
