### ISSUE TITLE
Remove deprecated [ERROR] Follow Ups email

### ISSUE THREAD

**Issue by morisy** [MuckRock/muckrock#1208]
Currently the below email is sent daily to requests@muckrock.com. It's been supplanted by various tasks and so should stop being sent.

---------- Forwarded message ----------
From:  <info@muckrock.com>
Date: Thu, Jun 29, 2017 at 5:04 AM
Subject: [ERROR] Follow Ups
To: requests@muckrock.com, mitch@muckrock.com

ERROR: ack - 35437 - Washington Street, Brookline digging/gas work materials - <Response [400]>

ack - 27597 - 1033 Program Compliance Reviews (Department of Administration)
ack - 28363 - 2000 - Present DCRP forms (Bent County Correctional Center - CCA)
ack - 29038 - 2016 Clown Sightings (Sheriff's Office, Augusta-Richmond County, GA)

**Comment by mitchelljkotler** [comment]
I don't think these are logged anywhere else
