### ISSUE TITLE
2 Ghost Crowdfund Tasks

### ISSUE THREAD

**Issue by blipblitz** [MuckRock/muckrock#1220]
Even when I've cleared all of the Crowdfund tasks, there are still "2" associated with the label.
<img width="969" alt="screen shot 2017-07-27 at 10 50 00 am" src="https://user-images.githubusercontent.com/9257325/28676709-5e09345e-72b9-11e7-9936-a0da00173292.png">

**Comment by mitchelljkotler** [comment]
So JPat somehow created 3 crowdfunds for a single request, leaving 2 of the crowdfunds as "orphans".  Obviously just not showing up isn't a great failure model.  I've removed the offending crowdfunds and tasks for now, will try to figure out a way to prevent this from happening again.

**Comment by mitchelljkotler** [comment]
Attempted to fix the race condition, if you see this again, let me know
