### ISSUE TITLE
Improved handling of orphaned communications/moved communications privacy settings

### ISSUE THREAD

**Issue by morisy** [MuckRock/muckrock#1221]
Currently, if an agency sends an attachment to orphans or if an attachment goes to the wrong request, it either is considered public or inherits the permission settings of the wrong request. Settings are not reset on move.

Orphans should be considered “private” on document cloud in call cases, and then document cloud permission settings should be set on any move or clone action as well as orphan assignments.

**Comment by mitchelljkotler** [comment]
fixed before you could even file the bug

**Comment by morisy** [comment]
Both issues? You are a scholar and a gentleman.

**Comment by mitchelljkotler** [comment]
also for the record, orphan documents are never and have never been uploaded to document cloud - they simply had the file set to public in our database, and then got uploaded as public after being moved, regardless of the embargo status of the new
