### ISSUE TITLE
Better Project Cache Flushing

### ISSUE THREAD

**Issue by morisy** [MuckRock/muckrock#1224]
A user noted that when they added requests to their project, there was a delay when the project page was updated. Any edits/updates to a project on the front end should show up immediately by flushing the cache. Probably fine to not deal with when request statuses are updated by agencies, but also wonder how much of an issue it is to just have the cache get flushed every time a logged in user visits so they always see the latest?

**Comment by mitchelljkotler** [comment]
The cache will now be cleared after the project is edited.  Clearing the cache whenever a logged in user views it seems like an unnecessary performance hit.
