### ISSUE TITLE
Safari 10.10.5 errors

### ISSUE THREAD

**Issue by morisy** [MuckRock/muckrock#1237]
A user reported (via Twitter) some pretty bad design errors. I use Safari and have never had similar issues, so no idea what's going on:

![screenshot 2017-08-30 22 57 55](https://user-images.githubusercontent.com/136939/29904404-ad82317e-8dd6-11e7-8e3f-49994f2d607a.png)

![screenshot 2017-08-30 22 58 28](https://user-images.githubusercontent.com/136939/29904420-bcccb69a-8dd6-11e7-8771-e94b23ce37e1.png)

Will try to replicate.

**Comment by mitchelljkotler** [comment]
Any extensions they have installed?

**Comment by morisy** [comment]
Don't think so. Will try and mess around with this at some point. Had some people complain that old versions of Safari have this issue so hoping it's that though I feel like it's not.

**Comment by mrengy** [comment]
Looks okay to me on Safari 9.0.3

![screen shot 2017-10-17 at 7 38 10 pm](https://user-images.githubusercontent.com/2223603/31694514-cc4b010a-b372-11e7-99e9-455d75ec0c6a.png)

**Comment by morisy** [comment]
Closing out unless someone can replicate.
