### ISSUE TITLE
Duplicate Jurisdiction (Beaux Arts, WA)

### ISSUE THREAD

**Issue by blipblitz** [MuckRock/muckrock#1244]
Apparently, these two jurisdictions are actually the same place. Let me know if there's a preference for which gets deleted, etc. 

h/t Phil Mocek: https://www.muckrock.com/task/flagged/157609/

<img width="794" alt="screen shot 2017-09-11 at 9 36 17 am" src="https://user-images.githubusercontent.com/9257325/30277075-baff8ac0-96d4-11e7-8414-a97bb81fbc43.png">

**Comment by morisy** [comment]
Thanks! Deleted Beaux Arts, WA and updated #693 to also include merging jurisdictions (Should be extremely rare) and created #1248 to add Jurisdiction Aliases, which is somewhat less rare.

In general, Github should be reserved for software-related issues.

Content and data quality issues like this should be handled via flags and on Slack.
