### ISSUE TITLE
FOIAMachine.org requests all throw 500 errors

### ISSUE THREAD

**Issue by morisy** [MuckRock/muckrock#1251]
If you log into MuckRock and click one of your requests, you get a 500 error. No error number is shown.

**Comment by morisy** [comment]
Via a user:

> A researcher working with me and using the same account just reported it today, and now I'm seeing it, too. Not sure when he first noticed it but it would have been recent. Two things:
> -He says he created a draft request in recent days, but now can't access that draft.
> -But I just did a test draft request, and I can access the test. Hmm.

**Comment by mitchelljkotler** [comment]
I cannot reproduce this, I can view my foia machine requests fine.  Useful things to include in the bug report: the user who experienced the error and the actual request which throws the error.

**Comment by mitchelljkotler** [comment]
I reply too quickly - although all the relevant info is nice to have, I just remember I fixed a FOIA machine bug yesterday but did not push it yet.  I will release it tomorrow morning - it should fix this issue.
