### ISSUE TITLE
Link directly to an attachment to a request, in such a way that it shows the attachment

### ISSUE THREAD

**Issue by Asparagirl** [MuckRock/muckrock#1262]
I would love to be able to link directly to a new scanned attachment that has just come in on one of my requests, like this one...

https://www.muckrock.com/foi/buffalo-207/index-to-buffalo-death-records-through-december-31-1945-42763/#file-156488

...and have that link open the attachment itself, so everyone following the link (from, say, Twitter) can see the specific document I'm referencing.

**Comment by mitchelljkotler** [comment]
Next to the view link is the embed and download link - the download link goes directly to the PDF.  Is this what you are asking for?  Although we prefer linking to request page with the embedded document, as it gives context, you should be able to link directly to the PDF if you need to.

**Comment by Asparagirl** [comment]
I don't want to link people to a PDF file, I want to link to a web page that is displaying your document viewer, so they can view the PDF in your page.  I can do that if I'm browsing the request page and click "View".  But right now I can't actually link to that view.

**Comment by mitchelljkotler** [comment]
Ah, ok, I see what you mean.  I will try to fix it soon.
