### ISSUE TITLE
Disappearing dates? 

### ISSUE THREAD

**Issue by shawnmusgrave** [MuckRock/muckrock#1264]
Dates seem to be missing from correspondence on some request pages: 

See screenshots below and these request pages: 

https://www.muckrock.com/foi/massachusetts-1/julie-nassif-emails-tofrom-james-hanchett-42963/?
https://www.muckrock.com/foi/united-states-of-america-10/margaret-thatcher-state-1991-to-2000-9008/?

![screen shot 2017-10-19 at 10 20 11 am](https://user-images.githubusercontent.com/7838930/31775619-20e13082-b4b7-11e7-8449-686d578c3778.png)
![screen shot 2017-10-19 at 10 19 52 am](https://user-images.githubusercontent.com/7838930/31775620-20ef6f26-b4b7-11e7-89f3-bd9ec9166e23.png)
![screen shot 2017-10-19 at 10 19 43 am](https://user-images.githubusercontent.com/7838930/31775621-20fb502a-b4b7-11e7-870a-a8822976891b.png)

**Comment by mitchelljkotler** [comment]
Tthe fix was in flight before I saw this issue, but thanks for reporting
