### ISSUE TITLE
Snail Mail chokes + tweaks

### ISSUE THREAD

**Issue by morisy** [MuckRock/muckrock#1275]
Not a promising start for its first day on the job, but snail mail was choking (to be fair, there are now 115 snail mails to go out).

Also wonder if it's worth keeping a permalink to the generated PDFs for later diagnostic/recovery purposes? I can imagine a scenario where someone spills coffee right before things go out and we need to reprint part, but tasks got already checked off or some other human error.

**Comment by mitchelljkotler** [comment]
Performance should be better now

For the second point - from the snail mail task page you can generate a single PDF for any task, as well as generating the bulk PDF for all open tasks.  Whenever you generate the PDF through either of these methods, it will save the PDF to the communication's mail communication.  You can view this on the request page in the gear drop down - similarly to how you can view a raw email.

Just to be clear - if you get the PDF from the snail mail task page - either for one task or for all open ones - it will regenerate all of the PDFs and save them (possibly overwriting) to the communication.  This allows for making any fixes to the request if an error is noticed in the PDF.  On the communication, it will always show you the PDF that was generated (and presumably mailed) - it will never regenerate the PDF and if the PDF has not been generated yet, will not show you anything.

So single PDFs are always saved - the bulk PDF is not.  Is there a desire to save the bulk PDF?
