### ISSUE TITLE
Cancelled Pro user accounts should retain account features through end of account term

### ISSUE THREAD

**Issue by morisy** [MuckRock/muckrock#1289]
If a Pro users account subscription renews on Jan. 1, and they've only used 10 requests of their 20, and they then cancel on the 15th, they should not lose the 10 other requests or ability to embargo until Feb. 1. I feel like Stripe has some kind of handling for this so that the subscription cancellation period doesn't close until whenever they've paid through.

Same principal applies to Org accounts.

**Comment by mitchelljkotler** [comment]
This happened at some point
