### ISSUE TITLE
Add little visual representation of contribution flow

### ISSUE THREAD

**Issue by patcon** [MuckRock/muckrock#1296]
A small addition for when new contributors are orienting would be to use gitgraphs.js to render a simple visual explanation under the README's "Deploy" section. This could also go in a `CONTRIBUTING.md` file in the future, and replace a bunch of verbose text that would normally help orient newcomers.

https://github.com/nicoespeon/gitgraph.js

![screenshot of a rendered graph](https://i.imgur.com/qCsN8tg.png)

**Comment by morisy** [comment]
Really interesting idea. Maybe come back to it once we have a better onboarding process and more contributors?
