### ISSUE TITLE
Create new labels

### ISSUE THREAD

**Issue by patcon** [MuckRock/muckrock#1297]
Would it be sensible to create these two labels?

- `documentation`. For people generally interested in improving overall project documentation in various ways.
- `first-timers-only`. To allow people to start tee'ing up simple and atomic issues that are specifically intended to be completed by persons with no experience on the project, as a way to engage further. The specific lingo helps communicate the right message to both newcomers ("you're welcome to join") and mature contributors ("pls don't touch this one")

Thanks for your consideration!

**Comment by morisy** [comment]
I like both of these ideas. Closing this for now to continue discussion on Slack and merge with #1299 which has some overlap.
