### ISSUE TITLE
Staging website not accessible

### ISSUE THREAD

**Issue by patcon** [MuckRock/muckrock#1298]
Heyo!

I'm running into this when trying to access staging website at http://muckrock-staging.herokuapp.com/:

![screenshot of http://muckrock-staging.herokuapp.com/](https://imgur.com/Nv4jiYJ.png)

This occurs when accessing from both my coworking space and my mobile data plan.

Is this expected behaviour? If so, how is the filtering happening, so that I can go about investigating what may have happened? Thanks.

**Comment by mitchelljkotler** [comment]
This is expected behavior, staging is restricted to employees.

**Comment by patcon** [comment]
Cool! Thanks a bunch for the info. Any plans for a test website that would be possible for non-employees to more easily work with?

**Comment by mitchelljkotler** [comment]
Do you have a use case in mind?  For general development, a local installation makes the most sense.  The Vagrant set up should make this less painful to set up for local development.  The current staging site is mainly used to share changes internally before they are ready for production and to test out features which may be impacted by being in an actual server setting on Heroku as opposed to the local dev environment.

**Comment by patcon** [comment]
For sure. For context, my background is in devops and working with communities who try to organize in an inclusive way around digital tools (for example, the civic tech scene).

I've found it very welcoming to unexpected sorts of participation when people who you might not expect to contribute (and who likely don't know how to spin up dev environments) can participate in discussion. This tends to be around pull requests. Welcoming that participation before the big merge/no-merge decision is made can unlock non-technical sorts of contribution and ownership of decisions and product.

In particular, Heroku Review Apps are amazing for letting everyone easily view changesets. When you need to spin up a dev environment in order to hold an opinions on a change, then it limits who can have power in that discussion :)

Here's an example of a repo that uses Heroku review apps to auto-deploy changes, and allow lots of non-technical academic stakeholders to chime in: https://github.com/edgi-govdata-archiving/100days/pull/95

(Most of the convo happens in slack, not github issue. But it's a start! These folks definitely wouldn't be able to have a say in pending pull requests without that.)

That group also happens to have a working group that does work via MuckRock. I am imagining a hypothetical future where there was a publicly visible test website, and pull requests were auto-deployed to a review apps. Now, should that team express frustration in the website, or a desire that I suss out as a feature request -- then I could come here and initiate that process, and pull them into it. This would give that group a different relation to the MuckRock website itself. It would no longer be a static thing delivered to them, but a thing that they could perhaps imagine being part of improving. This might lead to happy outcomes like them portioning money for developer time, or some such thing that might not arise otherwise :)

Anyhow, I'm very enthusiastic about not just open code, but open and inclusive process. Happy to brainstorm ideas further if this is something that staff MuckRock developers would also be curious to explore :tada:
