### ISSUE TITLE
Participate in up-for-grabs.net for expanding contributor community

### ISSUE THREAD

**Issue by patcon** [MuckRock/muckrock#1299]
Would participating in [up-for-grabs.net](up-for-grabs.net) be of interest to project maintainers, if someone wanted to help lay groundwork for that?

Background information: https://nikcodes.com/2013/05/10/new-contributor-jump-in/

How to: https://github.com/up-for-grabs/up-for-grabs.net#add-a-project

**Comment by morisy** [comment]
Hey! Sorry for the delay but would love to chat about this morning. Really like the idea, not sure what's the best way to run through getting it set up.

**Comment by patcon** [comment]
I would say that first steps could be:
- [ ] Create an engaging self-directed onboarding process, with all the context someone needs to start caring and working on this project -- primer readings/videos, dev environment setup, team member intros, saying hi, first PR, triage walkthrough, etc. etc ([Example](https://trello.com/b/FCGGEaQq/edgi-web-monitoring-project-dev-onboarding))
- [ ] Create a low-barrier public chat channel
- [ ] (optional) bridge public chat channel to where devs and stakeholders like (a special Slack channel?)
  - [this bridge](https://github.com/edgi-govdata-archiving/matterbridge-heroku) can be run on heroku for $7/month, which is totally worth it to unfuck the fragmented chat landscape that Slack has created :)
- [ ] create a `first-timers-only` label
- [ ] tee up some really well-documented issues, and tag them
- [ ] Submit a PR to up-for-grabs.net

**Comment by patcon** [comment]
## inspiration

- starting from the newcomers guide: https://coala.io/#/getinvolved (could just be in readme -- no need for special webpage)
- clean readme + emoji :heart:: https://github.com/kazupon/vue-i18n#readme
