### ISSUE TITLE
Limited permissions group for interns

### ISSUE THREAD

**Issue by morisy** [MuckRock/muckrock#1329]
Create a more limited permissions group for interns.

**Comment by mitchelljkotler** [comment]
We should also have a group for staff and for helpers (Alpha) and remove super user status from all users.

The question is what permissions they should have.  (By default, models have add/change/delete permissions)
- Helpers - do they log in to the backend ever?  I don't think they need any permissions, being non-super user staff will give them access to the tasks

- Interns - I don't think they need delete permissions, but do need add/change permissions on some subset of our models

- Staff  - add/change/delete on a greater subset of the models
