### ISSUE TITLE
Templating of assignments using variables from CSV

### ISSUE THREAD

**Issue by morisy** [MuckRock/muckrock#1339]
Following on from #1338, let users use some kind of variable name in description, questions (and answers, if possible) etc, so that a user could upload a CSV along the lines of:

Embed, Name, State, School
https://www.documentcloud.org/documents/4355034-Philip-R-Martinez-Financial-Disclosure-Report.html, Philip Martinez, Michigan, University of Chicago

and then have a question like:

"Did the document indicate /[Name] graduate from /[School]?"

**Comment by mitchelljkotler** [comment]
this work has been started on covidpublic.info
