### ISSUE TITLE
Ability for users to "skip" question if data is bad or not sure what to do

### ISSUE THREAD

**Issue by morisy** [MuckRock/muckrock#1340]
Users should have the ability to skip a given question, ideally with some way to flag why they want to skip it (data is illegible, instructions unclear or nonsensical, too much work).

I think if we start with Skip and then maybe an option field to explain why they're skipping that would be good beginning.

**Comment by shawnmusgrave** [comment]
Might want to allow skipping of an entire assignment — if entire page is illegible

**Comment by morisy** [comment]
Just store a "Skip" column and include data if they entered it so they can filter or rework questions or remove bad data.
