### ISSUE TITLE
"Submit" button doesn't actually submit the request

### ISSUE THREAD

**Issue by b-meson** [MuckRock/muckrock#1353]
<img width="1405" alt="screen shot 2018-02-11 at 4 05 56 pm" src="https://user-images.githubusercontent.com/3100220/36079148-80ef15be-0f45-11e8-8664-fb6e449845f0.png">
This is a UX/UI issue with MuckRock. If you create a new request, the UX/UI shows you to "submit" but it sends you to a "preview-type" route. This is a bit unsettling to new users unfamiliar with MuckRock.

**Comment by morisy** [comment]
We've tried a few different terms and haven't found anything that's relatively short that works super well. Do you have suggestions?

Do you think "Create Request" is more accurate/less confusing, and then "Submit Request" on next page?

"Draft Request" on first page and then "Submit Request" on second?

**Comment by b-meson** [comment]
Thanks for the historical background @morisy. I think "Preview Request" and "Submit" would work well in this case.

**Comment by mitchelljkotler** [comment]
new composer makes this obsoleote
