### ISSUE TITLE
Feature request: more links on organization page to existing FOIAs

### ISSUE THREAD

**Issue by HongPong** [MuckRock/muckrock#1357]
If I go to https://www.muckrock.com/organization/orgname it would be nice if there was a small text link - it could be right floated next to Recently Filed. It would say "show all recently filed requests" and go to a paginated view. And same for Recently Completed. It's not too clear where to click to get the list of everything.

**Comment by mitchelljkotler** [comment]
I've added a list for requests from your own organization and appropriate links from the org page if you are viewing your own org.
