### ISSUE TITLE
Spike in 503 error requests

### ISSUE THREAD

**Issue by morisy** [MuckRock/muckrock#1361]
Rapidly doing some kinds of tasks leads to a spike in 503 errors pretty regularly. It's not a huge deal if it only impacts admins, but just wanted to flag in case it's appearing for users doing normal user things, like listening to human music.

Able to replicate by quickly opening a bunch of requests in tabs, and then running through them and quickly trying to open the admin view. Over 20% of the time I get a 503.

**Comment by mitchelljkotler** [comment]
This is on purpose to prevent DoS attacks - I can change the limits if you are so fast you appear to be a DoS bot :robot:
