### ISSUE TITLE
Pull lots of DocCloud links from requests/projects.

### ISSUE THREAD

**Issue by blipblitz** [MuckRock/muckrock#1366]
We'll need a way of bulk adding associated documents from a bunch of requests to the Assignment tool.

**Comment by knowtheory** [comment]
This is blocked on meeeeeeee.

**Comment by mitchelljkotler** [comment]
@knowtheory - This issue in particular is to be able to pull multiple documents into the crowdsourcing tool all within MuckRock.  For example, search/filter for a set of your requests, then add all documents from those requests to a crowd source.
