### ISSUE TITLE
Automatically handle FOIA Online notifications

### ISSUE THREAD

**Issue by morisy** [MuckRock/muckrock#1377]
Some FOIA Online emails can be automated. For example, it automatically sends out these, that don't require any user interaction:

"In 4 days from the sending of this message, your FOIAonline user account password for [ email inserted here ] will lock due to inactivity. To prevent this from happening, please log into the FOIAonline application and reset your password."

**Comment by mitchelljkotler** [comment]
That sounds like it requires user interaction, we don't want the account to lock, do we?
