### ISSUE TITLE
! How do user responses get sent via portal?

### ISSUE THREAD

**Issue by blipblitz** [MuckRock/muckrock#1378]
https://www.muckrock.com/foi/united-states-of-america-10/social-security-and-incarceration-47086/

The user responded to the agency, but the request was set to portal (appropriately) and the response didn't make it to the agency. 

It was only caught because the user flagged the most recent communication, which got cut off after the greeting.

**Comment by morisy** [comment]
Is this still an open question/bug or did it get resolved?

**Comment by morisy** [comment]
Closing this out, but if it's still an issue please re-open with more details.
