### ISSUE TITLE
Check that Mailed communications are getting marked as "Mail"

### ISSUE THREAD

**Issue by blipblitz** [MuckRock/muckrock#1401]
It seems as though some communications are sent via Mail and the communication is sometimes left marked as "None."

This happened here, but then the request was Emailed, so that changed the communication status. 

https://www.muckrock.com/foi/new-york-city-17/inventory-listing-of-all-microfilm-and-microfiche-holdings-of-the-new-york-city-municipal-archives-50397/

**Comment by mitchelljkotler** [comment]
It should be marked as "Mail" when the PDF is generated - if you have an example / can reproduce it not being marked correctly after the PDF is generated, reopen
