### ISSUE TITLE
Download all as ZIP button not appearing for Org members

### ISSUE THREAD

**Issue by pierwill** [MuckRock/muckrock#1405]
For when they attach each email as a pdf...

https://www.muckrock.com/foi/illinois-168/illinois-state-police-counter-terror-liason-52205/#files

**Comment by morisy** [comment]
Hi! Sent you an email follow up on this; will update here if it needs to be updated.

**Comment by morisy** [comment]
I could be missing something, but I believe @pierwill is an active Org member, but when I checked user does not have access to the "Download as Zip" tool, which they should have access to.

**Comment by pierwill** [comment]
👍 Thanks!
