### ISSUE TITLE
Handling responses to deleted requests.

### ISSUE THREAD

**Issue by blipblitz** [MuckRock/muckrock#1413]
We should have a better system for dealing with emails that are responding to requests that have been deleted. Though we shouldn't often be deleting requests, we do run into this situation with enough frequency that it should really have a systemized method for handling. This might include our own sort of "out of office" reply to let the agency know that the request is no longer active.

**Comment by mitchelljkotler** [comment]
We now have an auto reply that the request has been withdrawn
