### ISSUE TITLE
Alter already submitted Assignment response

### ISSUE THREAD

**Issue by blipblitz** [MuckRock/muckrock#1416]
I can imagine situations in which someone might want to easily alter a response for an internal Assignment project or scrap a response and do the Assignment again.

For example: A few response into this Assignment (https://www.muckrock.com/assignment/tennessee-valley-authority-talking-points-49/#assignment-responses), I decided to change the way I was making notes. I would like, in these situations, to be able to scrap the previous Assignment responses and just do them again.

**Comment by morisy** [comment]
Related:

* Ability to delete an assignment submission
* At least admin accessible reversion tracking in place for this feature
* Coral Ask included the ability to edit submissions for Gallery review. I think having the ability to see original vs. edited is nice, but might be fine to just show whatever the latest is and note that it was edited by Username.
* Coral does not allow editing of original entries. I can imagine some potential abuse depending on how permissions are handling and how we present data, so at least noting a change was made and who made it is important (one vector for example would be to let users edit their submissions. if someone had a gallery item selected, for example, they could edit it to deface the gallery site).

![screen shot 2018-06-04 at 9 16 00 am](https://user-images.githubusercontent.com/136939/40919802-8e27127c-67d8-11e8-8c8a-c51f4e9c6e6a.png)

**Comment by mitchelljkotler** [comment]
You can now edit assignment responses
