### ISSUE TITLE
Discuss date shown on communications

### ISSUE THREAD

**Issue by morisy** [MuckRock/muckrock#1420]
We've gotten a few reports from users who were felt the date on the communication was not the date that the communication was actually sent. I'm trying to figure out if this is a bug, intentional, or if there's some way we can improve clarity on this issue. Just want to discuss — no changes until we run through:

* What should be happening in an ideal scenario
* What might be preventing that now
* What we think is best for users

**Comment by mitchelljkotler** [comment]
Always show latest date
