### ISSUE TITLE
Vagrant Issues

### ISSUE THREAD

**Issue by morisy** [MuckRock/muckrock#1428]
— Vagrant Up did not work with latest version of Vagrant.
  * Works first time, but if you suspend and then use Vagrant up again, there is an issue with shared folders.
— Seems like a virtual box vision provisioning issue.

```

output : of vagrant reload
==> default: Checking if box 'bento/ubuntu-16.04' is up to date...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
   default: Adapter 1: nat
   default: Adapter 2: hostonly
==> default: Forwarding ports...
   default: 8000 (guest) => 8000 (host) (adapter 1)
   default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
   default: SSH address: 127.0.0.1:2222
   default: SSH username: vagrant
   default: SSH auth method: private key
   default: Warning: Connection reset. Retrying...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
   default: The guest additions on this VM do not match the installed version of
   default: VirtualBox! In most cases this is fine, but in rare cases it can
   default: prevent things such as shared folders from working properly. If you see
   default: shared folder errors, please make sure the guest additions within the
   default: virtual machine match the version of VirtualBox you have installed on
   default: your host and reload your VM.
   default:
   default: Guest Additions Version: 5.1.22
   default: VirtualBox Version: 5.2
==> default: Configuring and enabling network interfaces...
==> default: Mounting shared folders...
   default: /home/vagrant/muckrock => /home/ben/CFB/muckrock
   default: /tmp/vagrant-puppet/modules-3d22170244fcc601ef0e406a910e5adb => /home/ben/CFB/muckrock/puppet/manifests/modules
   default: /tmp/vagrant-puppet/manifests-846018e2aa141a5eb79a64b4015fc5f3 => /home/ben/CFB/muckrock/puppet/manifests
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: flag to force provisioning. Provisioners marked to run always will still run.

```

**Comment by mitchelljkotler** [comment]
Did the shared folders not work?  From the output it looks like everything worked as expected

**Comment by BenjaminDoran** [comment]
To add more detail: 

Following the setup instructions with vagrant 2.1.1 and virtual box 5.2, initially works. The VM is created and I am able to SSH in. If however `vagrant suspend` or `vagrant halt` are called, vagrant loses its ability to reestablish network connection to the VM when using `vagrant up`. Calling `vagrant up` results in a timeout message. The VM is running, but SSH no longer works. (also times out)

If I instead run `vagrant reload`, I see the output from above and vagrant is able to reestablish networking. Looking at the output above seems to give the most clues that this is a versioning issue with virtualbox, setting up network connections and shared folders.

I'll paste the output of `vagrant up` and `vagrant ssh` soon

**Comment by BenjaminDoran** [comment]
So, I tried installing virtualbox 5.1 and then upgrading to 5.2, and I am now unable to replicate the errors I was seeing before. :confused: 

It seems like there is some configuration file or something that is needed from 5.1, but is not removed when it is uninstalled.

This really seems to just be an incompatibility between virtualbox 5.1 and 5.2. Useful information for any incoming devs but no changes seem to be needed in the project.

**Comment by mitchelljkotler** [comment]
we no longer use vagrant
