### ISSUE TITLE
Article slug generator using different time zone than other URL checkers

### ISSUE THREAD

**Issue by morisy** [MuckRock/muckrock#1564]
So 90% certain that I understand this issue.

With some articles, the slug used by the actual URL page is based on Eastern time, while in other places its GMT (I think), meaning that articles published very late in the day generate bad links when put on the homepage or when you use the “view on site” link from admin.

For example, the most recent article about 50,000 requests generates this url in various places:

https://www.muckrock.com/news/archives/2018/jul/15/whole-lot-transparency-muckrock-users-file-50000-r/

When it should be:

https://www.muckrock.com/news/archives/2018/jul/14/whole-lot-transparency-muckrock-users-file-50000-r/

**Comment by mitchelljkotler** [comment]
timezones are terrbile
