### ISSUE TITLE
Proxies linked to state page backend.

### ISSUE THREAD

**Issue by blipblitz** [MuckRock/muckrock#1579]
I'd like to see who the proxies are from the state page.

**Comment by morisy** [comment]
This should be available from the bottom of any state that uses proxies, unless you're looking for something else?
 
![screen shot 2018-07-31 at 9 54 08 am](https://user-images.githubusercontent.com/136939/43463876-b100578a-94a7-11e8-9b6e-8f6406d94362.png)
