### ISSUE TITLE
Portal info disappears

### ISSUE THREAD

**Issue by pierwill** [MuckRock/muckrock#1584]
Not sure how to reproduce this issue, but frequently the link for portal login credentials will disappear from specific request pages of mine. Usually involving nextrequest.

**Comment by mitchelljkotler** [comment]
Can you give an example of a request where this has happened?

**Comment by pierwill** [comment]
(sent through another channel)

**Comment by mitchelljkotler** [comment]
This was an error in how we process some of these requests.  I have added the portal info back on to the affected request.  This should not happen in the future - however if you have any other requests that were affected feel free to send them to me (either here or in private)
