### ISSUE TITLE
Contact Assignment Users Tool

### ISSUE THREAD

**Issue by morisy** [MuckRock/muckrock#1598]
A few things bundled together:

— A mail icon next to the edit icon, that when clicked presents a modal dialog similar to "Contact User" but also let you set "from" email address and subject line. Default from email address should be the sender's email address stored in the backend. This feature should be available to everyone at start. Do not show the Assignment submitter's email address.
— For admins only (for now), include email address of submitter in the CSV download next to the related entry. Will work on more fine grained permissions for this going forward.

**Comment by mitchelljkotler** [comment]
Should there be a limit to how many times someone can message a user?

**Comment by morisy** [comment]
Not to start. We can implement over time. Make sure to log to diagnostics
for abuse prevention purposes.
