### ISSUE TITLE
Plans page doesn't let organization uses do anything.

### ISSUE THREAD

**Issue by morisy** [MuckRock/muckrock#1599]
<img width="1053" alt="screen shot 2018-09-03 at 8 14 12 am" src="https://user-images.githubusercontent.com/136939/44986353-71b99680-af51-11e8-9faa-c503f665c07f.png">

The Plans page is pretty much non-useful if you own an Org. That green button should take you to the organization page:

https://www.muckrock.com/organization/whatevertheirorganizationis/

And underneath the button it should have italicized text that says something like: "To switch plans, first [deactivate your Organization account](https://www.muckrock.com/organization/whatevertheirorganizationis/). You can also add or remove users there."

**Comment by mitchelljkotler** [comment]
Obsolete with squarelet
