### ISSUE TITLE
Auto followups going out too frequently

### ISSUE THREAD

**Issue by morisy** [MuckRock/muckrock#1610]
It looks like this jurisdiction is sending out autofollowups every three days, instead of every two weeks as expected:

https://www.muckrock.com/admin/foia/foiarequest/50028/change/

**Comment by mitchelljkotler** [comment]
I'm not sure what you are looking at, but the request you linked is sending out auto follow ups every 2 weeks

**Comment by morisy** [comment]
Sorry, meant this one: https://www.muckrock.com/admin/foia/foiarequest/26528/change/

**Comment by mitchelljkotler** [comment]
If a request has not been acknowledged, we follow up in the number of days allowed by the applicable law (3 in Louisiana).  Should we only set the first follow up to use the legal limit?  Should we just ignore the legal limit entirely and always use 2 weeks?

**Comment by morisy** [comment]
First one uses legal limit, all subsequent ones 2 weeks
