### ISSUE TITLE
Generate password for all requests, not just portal requests

### ISSUE THREAD

**Issue by morisy** [MuckRock/muckrock#1611]
All requests should have an associated password, so that if a portal is associated after the fact the admin has an easy, secure password they can grab. Right now, we have to go to third party websites to generate passwords which slows down the process and means different processes for handling these types of tasks.

**Comment by mitchelljkotler** [comment]
If you add a portal to a request, the portal task should automatically create a password to use - we should go through the flow to see where the disconnect is
