### ISSUE TITLE
Add list of followed requests

### ISSUE THREAD

**Issue by jlg97** [MuckRock/muckrock#1615]
Add the the ability too see a full list of requests the user has followed along with the the ability to unfollow them.

**Comment by mitchelljkotler** [comment]
There is a list of requests you are following here: https://www.muckrock.com/foi/list/following/
There is a link to this page on the side bar from any list of requests page.

You may unfollow requests both from their individual page (there is a button at the top), or from the list page above, by checking the checkboxes next to the requests you wish to unfollow, then selecting "Unfollow" from the dropdown menu at the top of the page.

If you need more help with this, please let me know.
