### ISSUE TITLE
Plan/Billing Mismatch

### ISSUE THREAD

**Issue by ingalls** [MuckRock/muckrock#1618]
Was adding another member to our org and noticed that there is a mismatch between the plan displayed in settings (incorrect) and the plan displayed on the plan selection page (correct)

_Incorrect Plan on Settings Page_
![screenshot from 2018-11-01 09-06-51](https://user-images.githubusercontent.com/1297009/47853589-95645600-ddb5-11e8-8050-445230ef2e20.png)

_Correct Plan on Selection Page_
![screenshot from 2018-11-01 09-07-54](https://user-images.githubusercontent.com/1297009/47853610-a44b0880-ddb5-11e8-88d1-3d6adb1853ec.png)

cc/ @morisy

**Comment by morisy** [comment]
Thanks so much for catching this!
