### ISSUE TITLE
Add option to select multiple choices

### ISSUE THREAD

**Issue by blipblitz** [MuckRock/muckrock#1620]
It would be helpful to have an option by which a user could consult a list of options and select as many as applied.

**Comment by morisy** [comment]
Is this for Assignments? Does having the tick box option multiple times fit the needed criteria?

**Comment by blipblitz** [comment]
Hi! Revisiting this. I thought that the separate checkboxes might work, but without the ability to provide a single line of description that applies to each checkbox, it gets a little unwieldy. 

For example, I would like to create an Assignment entry right now that looks like: 

Where does this agency get its facial recognition data? (Check all that apply.)
[...] license photos
[...] booking photos
[...] Facebook
etc.

**Comment by morisy** [comment]
From https://formbuilder.online let's add Select and Checkbox Group.

**Comment by mitchelljkotler** [comment]
The problem with this is the one values are stored - it assumes one value per question.  There are ways around this but it needs to be thought about
