### ISSUE TITLE
Private projects not displaying requests within them

### ISSUE THREAD

**Issue by morisy** [MuckRock/muckrock#1645]
A user wrote in to say that when they were invited to look at [requests on a private project](https://www.muckrock.com/project/automobile-gps-tracking-359/), they were not appearing. When I clicked edit I could see the project, it looked like their were three that they're not showing in the draft project view. (They an also be viewed when [putting the project in as a filter](https://www.muckrock.com/foi/list/?q=&status=&user-autocomplete=&agency-autocomplete=&jurisdiction-autocomplete=&projects-autocomplete=&projects=359&tags-autocomplete=&has_embargo=&has_crowdfund=&minimum_pages=&date_range_0=&date_range_1=&file_types=&search_title=).

The user also said they believe that there were a number of requests just missing from the page. Not sure if that was a save problem or what; I'll keep looking into that as well.

**Comment by mitchelljkotler** [comment]
I see three requests on that project - on the main page, on the edit page, on the admin, putting the project in as a filter, and hijacking the two users in the project and viewing as them - all match, showing all three requests.

**Comment by morisy** [comment]
Hmm maybe it was a caching thing? They were not showing up originally. Low priority, but can we make sure the cache is reset when saves to projects are made?

**Comment by mitchelljkotler** [comment]
Yeah - that part of the page is cached, so definitely a cache issue
