### ISSUE TITLE
Email Submit Warning Doesn't Allow Override 

### ISSUE THREAD

**Issue by morisy** [MuckRock/muckrock#1650]
If a user is submitting their first request and includes an email, they get the normal warning:

<img width="658" alt="Screen Shot 2019-04-26 at 1 35 15 PM" src="https://user-images.githubusercontent.com/136939/56825820-4f4df380-6828-11e9-88d9-1a1fba087f6e.png">

But the overide option just presents the request as a draft again rather than actually submitting.

**Comment by freedmand** [comment]
Minor grammar nit but "simple" -> "simply" in the message
