### ISSUE TITLE
Update landing page year

### ISSUE THREAD

**Issue by morisy** [MuckRock/muckrock#1658]
So Allan made a really nice landing page, but hardcoded "2016":

https://github.com/MuckRock/muckrock/blob/master/muckrock/templates/flatpages/landing.html

Can we hardcode 2019 so that we can test it with our new adwords campaign?

**Comment by mitchelljkotler** [comment]
Should we have it display the current year instead of hardcoding it to 2019?

**Comment by morisy** [comment]
Yes

via Newton Mail [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=10.0.14&pv=12.2&source=email_footer_2]
On Thu, May 9, 2019 at 9:16 AM, mitchelljkotler <notifications@github.com> wrote:
Should we have it display the current year instead of hardcoding it to 2019?
