### ISSUE TITLE
More discoverable Organization switching

### ISSUE THREAD

**Issue by morisy** [MuckRock/muckrock#1694]
Right now, members who join new orgs have a rough experience since they're still in their personal org by default. We have a few changes to make this process more discoverable:

a) When someone joins an Org, make that Org their active Org at that point.
b) Change the following sentence, with the text in parantheses linking to this URL: https://www.muckrock.com/accounts/settings/#organization

> You are currently working on behalf of the organization MuckRock (Switch to MuckRock, the Daily Planet, or your personal account).

If someone is in an organization but is using their personal account, add this line:

> You are currently filing from your personal account (Switch to MuckRock or the Daily Planet).

that also links to the aforementioned link.

If someone is an org with requests but is prompted to pay because they're currently filing from an org with zero requests, and another one of their orgs has available requests, show this:

> You have 0 monthly requests left and 0 purchased requests left. You are making 2 requests. You will need to purchase 2 extra requests, or [switch your active account to MuckRock, the Daily Planet, or the Daily Bugle](#), which have requests left you can use.

**Comment by morisy** [comment]
Additional, tweak the copy on this page:

"Choose active org:"

and then under the picker: "You can also change your current organizational page by hovering over your name (or tapping it on mobile), and then selecting the organization you'd  like to use from the selection that appears."

**Comment by mitchelljkotler** [comment]
> Change the following sentence,
> Additional, tweak the copy on this page:

It is ambiguous what sentences and pages you are referring to.

> When someone joins an Org, make that Org their active Org at that point.
Should we only auto-activate if they are not currently in an org?  I could see this being problematic joining a second organization

> with the text in parantheses linking to this URL: 
Do you think an inline drop down would be easier for people - no need to switch pages.  Shouldn't be too hard to implement

**Comment by morisy** [comment]
> It is ambiguous what sentences and pages you are referring to.

Sorry, this is the line on the filing request page, under the main text input area

Regarding the auto active a second org, I’m not sure. I don’t think it’s a huge deal either way, but I think you’d probably want to start acting on behalf of that new org.

RE: inline switcher, that would be ideal to have.
