### ISSUE TITLE
Agency merge times out

### ISSUE THREAD

**Issue by blipblitz** [MuckRock/muckrock#1695]
I'm trying to merge these two agencies:

https://www.muckrock.com/agency/united-states-of-america-10/us-department-agriculture-agricultural-marketing-service-5360/

https://www.muckrock.com/agency/united-states-of-america-10/united-states-department-of-agriculture-agricultural-marketing-service-8777/

When I hit the "Merge" button on either page, the process times out, saying that muckrock.com redirected me too many times and then redirects to the homepage with a red error message: "Authentication process canceled"

**Comment by morisy** [comment]
Was able to get this working ok just now; might have been temporarily blip. Can you re-open if you see it again?
