### ISSUE TITLE
Public Data Set View and user opt in tasks

### ISSUE THREAD

**Issue by morisy** [MuckRock/muckrock#1711]
If there are submissions marked as "Gallery," create a publicly viewable page at:

http://muckrock.com/assignment/slug-plus-id/data/

<img width="1469" alt="Public Data Set View" src="https://user-images.githubusercontent.com/136939/63652426-094d6180-c72e-11e9-9c7e-267d3b67dd08.png">

Also create an opt in (default to no public acknowledgement) on assignment pages that have at least one item marked "gallery":

<img width="533" alt="Screen Shot 2019-08-25 at 12 02 02 PM" src="https://user-images.githubusercontent.com/136939/63652613-2edb6a80-c730-11e9-97d4-6bdaaafeb5b9.png">

This setting should apply to all of a user's submissions for a given assignment. so that they can change their mind later and have the decision apply retroactively.

Let every answer item have a gallery toggle in the Assignment creation tool (currently, I think just the text field ones do).

Assignment submissions that have a gallery field and have been marked as gallery by a Assignment owner should be availalable publicly via API. If the submitter opted in to public credit, their name should also be available via API; otherwise should be noted as anonymous submitter, same as if they'd submitted via API. IP addresses should not be available to non-owner API user.

**Comment by morisy** [comment]
Add markdown processing for text area input viewing.

**Comment by mitchelljkotler** [comment]
> This setting should apply to all of a user's submissions for a given assignment. so that they can change their mind later and have the decision apply retroactively.

This will be stored per response (no where else to store it) - but we can have a way to turn them all on or off - but I'm not sure where we would have that setting

Where does the "Assignments can help crowdosurce large documents" link point to?

**Comment by mitchelljkotler** [comment]
I believe this is done
