### ISSUE TITLE
Separate fields for regular/appeal/past tracking numbers.

### ISSUE THREAD

**Issue by blipblitz** [MuckRock/muckrock#172]
It would be nice to have separate fields for the tracking number currently assigned to a request, past tracking numbers, and appeal tracking numbers. Sometimes we end up with a string of tracking numbers, and it would be neater for everyone if we could differentiate between them more effectively.

**Comment by morisy** [comment]
OK, so add a widget to the front end that admins and users can use to add new tracking numbers. When a new tracking number is added, don't remove the old one, just make it a "Previous" tracking number, and still display on request page under the current tracking number.
