### ISSUE TITLE
Error on Kavanaugh crowdsource

### ISSUE THREAD

**Issue by blipblitz** [MuckRock/muckrock#1726]
Hello! We got this message from a user: 

Just got a couple errors while working through some of the Kavanaugh confirmation hearing assignment docs. Not sure what I did to break things other than enter data into fields in different orders before submitting, but after going back, skipping the first doc and trying again on a different doc, I got the same error. ¯\\\_(ツ)_/¯

34fb959536724470a2d668fc64d1fa4e
e3729d5118594a76a183159940db57a8

Hope that helps!

Chris

**Comment by mitchelljkotler** [comment]
This was a unicode error, it was fixed about a week ago, should be ok now
