### ISSUE TITLE
Clearer indication of monthly charges on subscription page

### ISSUE THREAD

**Issue by morisy** [MuckRock/muckrock#1746]
The subscription page should more clearly indicate when prices are monthly or annual for the appropriate plans, as some users think it's a one-time charge and then are surprised by monthly billing:

![Screen Shot 2020-01-23 at 3 40 21 PM](https://user-images.githubusercontent.com/136939/73022010-b5d36280-3df6-11ea-8f03-efe961cae156.png)

In the above image, I think it would suffice to just change to $40 / month in the green text.

**Comment by mitchelljkotler** [comment]
This was done
