### ISSUE TITLE
Add back email, address fields to agency API

### ISSUE THREAD

**Issue by morisy** [MuckRock/muckrock#1759]
During some refactoring, the address and email fields look like they were dropped. Fields that are stored like address, email, and phone should be available (email for Pro, Org and admin users) along with request type and email type.

**Comment by mitchelljkotler** [comment]
So address and phone should be publicly available?  And do you want the primary one for each, or all that we have on file?

**Comment by morisy** [comment]
Hmm I was thinking publicly available but I'm also fine with limiting to just Pro/Org/Admin. And I would have each on file.
