### ISSUE TITLE
Project page request count seems to cap at 191?

### ISSUE THREAD

**Issue by blipblitz** [MuckRock/muckrock#1768]
There are nearly 400 requests associated with this project, but the page count only shows 191. 

https://www.muckrock.com/project/new-york-officer-misconduct-and-disciplinary-materials-778/

**Comment by morisy** [comment]
I think this is probably a cache issue. Hacking History properly shows in the 600s. Reopen if it doesn't resolve later today?

https://www.muckrock.com/project/hacking-history-419/
