### ISSUE TITLE
Weird date on updated request

### ISSUE THREAD

**Issue by blipblitz** [MuckRock/muckrock#1780]
It says 3/2/2029. 

https://www.muckrock.com/foi/united-states-of-america-10/records-relating-to-ethics-pledge-us-department-of-education-37201/

<img width="653" alt="Screen Shot 2020-09-07 at 11 01 18 PM" src="https://user-images.githubusercontent.com/9257325/92428801-2482e780-f15e-11ea-87b3-b3f5b9bec0dd.png">

**Comment by morisy** [comment]
This was an error with file name while scanning, can be fixed from the admin side.
