### ISSUE TITLE
Automate response tasks with GPT

### ISSUE THREAD

**Issue by mitchelljkotler** [MuckRock/muckrock#1808]
Working with Gloo to implement this

**Comment by morisy** [comment]
Reviewed manual response tasks post-implementation vs. pre-implementation, and was surprised that by how many are still manual (531 tasks Oct. 1-15 vs. 811 tasks Sept. 1-15). Are the ones showing up ones GPT is flagging as can't evaluate, or something else going on?

https://www.muckrock.com/task/response/

**Comment by mitchelljkotler** [comment]
Gloo wasn't turned on until Oct 5, so a third of that time period is before it was turned on.

In addition, there were a couple of bugs in resolving tasks with Gloo, which I will resolve, which should help as well.
