### ISSUE TITLE
We need alt text on banner images

### ISSUE THREAD

**Issue by mitchelljkotler** [MuckRock/muckrock#1816]
Important for accessibility

https://www.muckrock.com/news/archives/2023/sep/12/foia-101-training-sept-20/

**Comment by mitchelljkotler** [comment]
The alt text is currently the article title - would you like a separate field to set alt text? @amandabee

**Comment by amandabee** [comment]
It wasn't obvious to me that it was there at all. 

On September 18, 2023 9:24:37 PM GMT+02:00, mitchelljkotler ***@***.***> wrote:
>The alt text is currently the article title - would you like a separate field to set alt text? @amandabee 
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/MuckRock/muckrock/issues/1816#issuecomment-1724237115
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
