### ISSUE TITLE
Add "Create Zendesk Ticket" in Processing view

### ISSUE THREAD

**Issue by mitchelljkotler** [MuckRock/muckrock#1823]
We would like the add "Create Zendesk Ticket" in the Processing view to offer a smoother process for reviewing and escalating tickets. This can be added as a column on the right side and includes the option to add a note. 

https://www.muckrock.com/foi/list/processing/

![Image](https://github.com/MuckRock/muckrock/assets/143415787/b1ade703-f697-45a6-a87e-7e428528e727)

**Comment by amandabee** [comment]
We didn't touch on this in today's call. @carruthm and I are wondering what kind of timeline we can expect? It would be helpful to have this done.

**Comment by amandabee** [comment]
You can already see all of the tasks that have a related ticket in the [processing view](https://www.muckrock.com/foi/list/processing/). What's missing is the ability to create a ticket from that view, and sometimes that is necessary.
