### ISSUE TITLE
Broken link with selector

### ISSUE THREAD

**Issue by ariccio** [MuckRock/muckrock#1825]
https://github.com/MuckRock/muckrock/blob/28780dd2057d39e3c11d8e430822f3aad0012cdf/muckrock/templates/crowdfund/widget.html#L11

I'm not entirely sure what happened. But several of those header tags have `id='id'`, which seems like some kind of typo. That would break things? I can't find the template for the faq page, or I'd submit a PR.

**Comment by mitchelljkotler** [comment]
Thank you for reporting, the IDs have been fixed.
