### ISSUE TITLE
Feature: Add stock response drop-down menu to request notes

### ISSUE THREAD

**Issue by eyeseast** [MuckRock/muckrock#1827]
Would like to add a feature request that includes a stock response menu when adding a note to the request page. 

Similar to the "Contact User" stock response drop-down menu.

![Image](https://github.com/MuckRock/muckrock/assets/143415787/70d57352-3050-4be6-a64f-49c418d50ff9)
![Image](https://github.com/MuckRock/muckrock/assets/143415787/afd8ee95-0d0d-4fd3-b450-26b7b397867f)

**Comment by amandabee** [comment]
We didn't touch on this in today's call. @carruthm and I are wondering what kind of timeline we can expect? It would be helpful to have this done.

**Comment by mitchelljkotler** [comment]
I can prioritize this - should be able to have it first week in Jan
