### ISSUE TITLE
More accessible color pallete for muckrock.com/place

### ISSUE THREAD

**Issue by mitchelljkotler** [MuckRock/muckrock#1829]
@eyeseast flagged that the current color palette for /place isn't particularly accessible. We're launching a feature based on a re-crunching of some data, and this seems like a good time to review and update how that's maps are illustrated to make them more accessible. Chris, would you be good for flagging any suggested improvements? I think this should be a light weight fix - we're currently planning the lunch of Alberts piece Monday Dec. 18th, so if possible would love to get updated by then (and if not, at least get it in motion)

**Comment by morisy** [comment]
Thanks to Chris talking through. For the short term article, we updated to use:

The states where the median cost for records is less than $50 are in <span style="background-color: #66C2A5;">green</span>, median costs between $51 to $100 are in <span style="background-color: #8DA0CB;">blue</span>, and median costs more than $100 are in <span style="background-color: #FC8D62;">orange</span>

There's some debate about whether it makes sense to have the stronger division vs. gradation division.

Also semi-related, but some people have trouble finding a given state and it might make sense to offer a state dropdown on that page to make it easier jump to state.

We also want to add the median cost map to the place page, similar to what was statically calculated for Albert's upcoming feature.

**Comment by morisy** [comment]
Colors:

#66C2A5
#8DA0CB
#FC8D62

**Comment by mitchelljkotler** [comment]
See #1834
