### ISSUE TITLE
Fix spelling of "journalistic"

### ISSUE THREAD

**Issue by amandabee** [MuckRock/muckrock#1847]
There are a lot of places on Squarelet and MuckRock's admin where we have spelled "Journalistic" wrong: 

`This organization is a verified jorunalistic organization`

I can live with it but I don't love it.

**Comment by duckduckgrayduck** [comment]
@amandabee I've identified all of the cases where this particular misspelling occurs and resolved them. If there any others you notice in the future, feel free to re-open this issue and I'll take care of it.
