### ISSUE TITLE
Assignments login error should be more clear

### ISSUE THREAD

**Issue by amandabee** [MuckRock/muckrock#1861]
https://muckrock.zendesk.com/agent/tickets/127461

> I am having trouble accessing [MuckRock's Slack channel](https://www.muckrock.com/slack/) which was amplified during that training. I am getting the error message: "User with this email already exists. Please login first. Email is required if registering with a name." I suspect this is because I subscribe to MuckRock emails. However, when trying to log in to the Slack channel, I get the error message "no account found."

The issue is that she needed to log in to Squarelet, not Slack. We should make that clear. Something like:

"It looks like `email` has an account on MuckRock -- please log in at https://accounts.muckrock.com and return to this form."

**Comment by mitchelljkotler** [comment]
Why do we use the embed URL for this when it is not embedded?  That hides the nav bar, which makes it confusing which site you are actually on.  If we use the URL at: https://www.muckrock.com/assignment/join-the-muckrock-foia-slack-24/form/
it is the same page, but it is clear you are on the MuckRock site.  I will update the error message also, wanted to raise this issue as well.

**Comment by amandabee** [comment]
Thanks for flagging that. I moved it to use the `form` version of the URL.
