### ISSUE TITLE
Agency Review Task - email and follow-up message not updating or sending

### ISSUE THREAD

**Issue by carruthm** [MuckRock/muckrock#1868]
Task was resolved with the new primary contact email but the new email did not update on the request and the follow-up email was not sent/did not appear on the request page. 

The new email in the example below is: lhoward@co.washington.ms.us. We can see this email is not on the backend of the example request below. 

We also used the following message in the text box but the old message is appearing on the resolved task: 
_To Whom It May Concern:
It appears that we directed the request copied below to the wrong email address or fax number at your agency. We wanted to follow up now that we have updated contact information. Please let us know when we can expect to receive a response.
Thank you for your help, and let us know if further clarification is needed._

Example: https://www.muckrock.com/task/review-agency/718189/ 

Request: https://www.muckrock.com/foi/washington-county-19524/use-of-force-policy-washington-county-sheriff-153432/

**Comment by mitchelljkotler** [comment]
Document how this works here:
https://www.notion.so/muckrock/Improve-Process-on-Review-Agency-Tasks-202f3c23d3494cc694590cae5c84f07e
