### ISSUE TITLE
Deal with spam on requests

### ISSUE THREAD

**Issue by mitchelljkotler** [MuckRock/muckrock#1875]

**Comment by mitchelljkotler** [comment]
We do not see spam too often, but occasional a request will be overrun with spam.  It is possible to manually close a request to further incoming email, which we can use to deal with this for now.  If it becomes a larger issue in the future, we can re-visit this.

**Comment by amandabee** [comment]
https://www.muckrock.com/foi/san-francisco-141/a-word-document-and-an-excel-file-immediate-disclosure-request-86453/ is an example of a request that was generating spam.
