### ISSUE TITLE
Proxys should be able to upload documents.

### ISSUE THREAD

**Issue by amandabee** [MuckRock/muckrock#1884]
I tried to share the upload URL and pass for a request with a proxy, b/c the agency sent them directly to him. Because he's logged in, he is getting redirected to the list of requests that he's filed, which means that he can't upload anything. 

Proxies should have access to the upload option.

**Comment by mitchelljkotler** [comment]
The upload URL and passcode is only for agencies.

Do we want proxies to have full edit access on all requests they are the proxy for?  So they can reply with attachments?

> Because he's logged in, he is getting redirected to the list of requests that he's filed, which means that he can't upload anything.

If we want him to impersonate the agency, he can just log out of his account (or use a private browser window) and then log in with the upload URL and passcode
