### ISSUE TITLE
When a user asks for help, I should be able to see that they have asked for help

### ISSUE THREAD

**Issue by amandabee** [MuckRock/muckrock#1885]
We are encountering some users who ask for the same help multiple times. This is something that comes up maybe quarterly -- not a huge issue, but also not a non-issue. 

https://www.muckrock.com/foi/grand-chute-33293/video-request-2024ct000281-howell-telisha-bouie-166574/ 

Users can't see the "yellow" boxes that show their queries at all. Only staff can see them. Exposing the Zendesk URL is going to be confusing to users, but it would be helpful if we could expose some of that information to the user. We could say something to them like "We'll respond by email -- check your inbox for messages from  MuckRock <support@muckrock.zendesk.com>"

![image](https://github.com/user-attachments/assets/9c5f4f2c-8a6f-493f-a4a3-f08b02e1a3b2)

**Comment by mitchelljkotler** [comment]
Users can see the yellow boxes

**Comment by amandabee** [comment]
Huh. I would swear I wasn't seeing it but I do see it. Excellent.
