### ISSUE TITLE
Registering for the MuckRock Newsletter buttons fail

### ISSUE THREAD

**Issue by duckduckgrayduck** [MuckRock/muckrock#1891]
In two different locations- both on top of release notes 

![image001](https://github.com/user-attachments/assets/cdea637f-e5e4-4c45-bc2c-08406d74e556)

and at https://www.muckrock.com/newsletters/ there are two different failures. 
https://drive.google.com/file/d/1o5AKvNn3Mz1ONHU5LDygJgl1SkSFjmDq/view?usp=sharing

The former shows a failure error, the latter the subscribe button doesn't do anything, while the DocumentCloud newsletter works.

**Comment by mitchelljkotler** [comment]
1. The release notes one fails because it is trying to sign up for a different newsletter - the release notes newsletter.  I am assuming this was retired at some point?  Should we just replace this with the normal newsletter?
2. That page looks absolutely awful.  It is using the MailChimp widgets instead of our form - I am not sure why it works, but I think we should either get rid of that page or redo it entirely.

**Comment by duckduckgrayduck** [comment]
1. Probably just substitute it with the MuckRock one where release notes get mentioned anyway
2. Since there is a signup on our homepage and on every news article, it's probably fine to eliminate this page, but pinging @amandabee for her opinion

**Comment by amandabee** [comment]
We definitely need a static URL somewhere that we can direct people to for newsletter signups. So we can't eliminate it. But we could expand on it for sure. 

We don't currently send anything to the DocumentCloud newsletter, but we will probably want to bring that back in some form.

**Comment by amandabee** [comment]
Don't hate me, but I think we should at least start sending a monthly DocumentCloud newsletter that's just what is new there. We can pull it from release notes. 

On July 30, 2024 12:19:50 PM PDT, Sanjin ***@***.***> wrote:
>1. Probably just substitute it with the MuckRock one where release notes get mentioned anyway
>2. Since there is a signup on our homepage and on every news article, it's probably fine to eliminate this page, but pinging @amandabee for her opinion
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/MuckRock/muckrock/issues/1891#issuecomment-2259043728
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mitchelljkotler** [comment]
These are all the projects that currently have newsletters attached to them.  I am going to turn the release notes one off.  I don't know if we want to disable any of the other ones.

Subjects Matter: FBI Files - Subjects Matter Newsletter
Hunting for Government's Oldest Computer - Get the Oldest Computer Newsletter
You Are Being Followed: Police Social Media Surveillance - MuckRock Project on Social Media Surveillance
Sunshine Spotlight: Massachusetts - Sunshine Spotlight: Massachusetts
MuckRock Canada - MuckRock Canada
Counting the Uncounted: The Sexual Assault Evidence Collection Kit Project - The Backlog
Algorithmic Control: Automated Decisionmaking in America’s Cities - Subscribe to the Algorithmic Control newsletter
Secret Scandals of the Trump Administration - Secret Scandals Of The Trump Administration Newsletter
The Private Prison Project - Sign up for the Private Prison newsletter
Unearthing CREST: CIA's Declassified Archives - Unearthing CREST Newsletter
America Bids on Amazon - America Bids on Amazon
Elections 2024 - MuckRock's Election Newsletter
State of State Public Records Laws - Subscribe to the MuckRock newsletter.
Air Quality Access: Data & reporting on air pollution's impact on Chicagoland - Air Quality Access
Release Notes: Contributing to MuckRock's open source efforts - Release Notes

**Comment by eyeseast** [comment]
Plan: Consolidate everything into one newsletter with tags to create segments.

One newsletter to rule them all.

**Comment by eyeseast** [comment]
Someone from @MuckRock/editorial can remove the DocumentCloud widget from this page: https://www.muckrock.com/newsletters/
