### ISSUE TITLE
Adding card charged numbers to receipts

### ISSUE THREAD

**Issue by carruthm** [MuckRock/muckrock#1892]
We think users should be able to see the last four digits of the card that was charged on their receipts. 

Examples of receipts: https://www.notion.so/muckrock/Examples-of-normal-receipts-196bc1032c8c4fb89e65e3aac392b3f3

**Comment by mitchelljkotler** [comment]
The last 4 used to be shown - a bug was introduced at some point that has been masking them ( I was unaware) - I will fix
