### ISSUE TITLE
Donation page updates

### ISSUE THREAD

**Issue by kellykauffman** [MuckRock/muckrock#1912]
**Error on page:**
- Green donate button doesn't work on mobile. Clicking on the donate button gives an error. (Screenshot attached)

**Here's some changes we'd like to make to the donate page:** 
- Remove "How would you like to donate?" and add a one-time/monthly toggle button below "Other Amount" 
- Remove email field
- Add a newsletter subscribe box below "Address" 
- 
![Screenshot_20240925-121716](https://github.com/user-attachments/assets/65cfded4-0621-4c92-8347-9e15e333aaca)

**Comment by amandabee** [comment]
Notes:

* Stripe asks for your email address again and I believe that Paypal does, too. So we should not ask twice.
* INN recommended getting the donate button closer to being above the fold on mobile. For that we need to tighten up the amounts and frequency. ProPublica has this consolidated a bit better, https://give.propublica.org/give/346423/#!/donation/checkout?c_src=141278

**Comment by amandabee** [comment]
In mid July, someone contacted Morisy because they were having a different issue donating on mobile and Morisy checked and confirmed that he could donate on mobile. So it's not clear when this issue started and it may not fully explain our donation drop off.

**Comment by amandabee** [comment]
If this will create an issue with tagging donors in Mailchimp, let's talk. We may need to pre-populate the email field in our form if you’re logged in or pass on the email address that you provided if you aren’t logged in.
