### ISSUE TITLE
Tagging newsletter subscribers in Mailchimp 

### ISSUE THREAD

**Issue by kellykauffman** [MuckRock/muckrock#1913]
We'd like to have all widget and embed subscribers tagged as Newsletter Subscribers (this is an existing tag) in Mailchimp, and to going forward making sure anyone who uses the widget or embed subscribed as a Newsletter Subscriber.

**Comment by morisy** [comment]
We can kill the specialized project-newsletter feature for now that subscribes you to both the main MuckRock newsletter as well as the project-specific newsletter.
