### ISSUE TITLE
Clicking "Switch to ..." link does not change your org 

### ISSUE THREAD

**Issue by amandabee** [MuckRock/muckrock#1915]
If I'm trying to file a request, I can see what org I'm working as. The info on how to change that is a link -- "Switch to..." but clicking the link takes me to a settings page that does not have any option for actually changing the org I'm using. 

![image](https://github.com/user-attachments/assets/9fc26f00-e2bf-4d17-ade9-b5ffdf4f7dae)

**Comment by mitchelljkotler** [comment]
Similar to #1894

**Comment by amandabee** [comment]
Ahh. Yes. This is the same issue. 

Closing as duplicate of #1894
