### ISSUE TITLE
Kentucky agencies missing "requires proxy"

### ISSUE THREAD

**Issue by carruthm** [MuckRock/muckrock#1918]
Some KY agencies are missing "requires proxy" marked on the backend. Kentucky state page is marked as proxy required but not all of the KY agencies are marked on the backend accordingly. 

We want checking the box on the state page to mark all of the agency under the state as "requires proxy". Right now, this is something we manually have to change. 

Examples: 
https://www.muckrock.com/admin/agency/agency/832/change/
https://www.muckrock.com/admin/agency/agency/20846/change/

Also, we should have "Proxy Required" noted somewhere on the front end of the agency page.

**Comment by eyeseast** [comment]
@mitchelljkotler is going to add some help text to differentiate the two proxy options.
