### ISSUE TITLE
Withdraw status changing to Awaiting Acknowledgement

### ISSUE THREAD

**Issue by carruthm** [MuckRock/muckrock#1919]
Issue flagged by Marabel. The video shows when she refreshes her request page after withdrawing the request status gets changed back to Awaiting Acknowledgment. (74 Projects): 

https://www.loom.com/share/f984ea6b9c6e4f23aa7de895f22e5547?sid=48fdb133-c089-431b-b11c-e27a2ce2d037

I tested it out on this request and didn't have an issue with the status reverting back to something else. https://www.muckrock.com/foi/minnesota-156/video-request62-cr-22-5689ahmed-evaan-yaser-166307/

**Comment by carruthm** [comment]
Marabel said it wasn't happening to all of the requests but here are more examples of when the withdraw status is reverting back: 

https://www.muckrock.com/foi/rock-county-8627/video-request-2022cf000172vance-camorius-a-167672/#
https://www.muckrock.com/foi/key-west-10238/video-request-168453/#
https://www.muckrock.com/foi/key-west-10238/video-request-168455/#
https://www.muckrock.com/foi/key-west-10238/video-request-168451/#
https://www.muckrock.com/foi/key-west-10238/video-request-168446/#
https://www.muckrock.com/foi/key-west-10238/video-request-167982/
https://www.muckrock.com/foi/key-west-10238/video-request22-mm-000382-a-kkender-ilara-167941/
https://www.muckrock.com/foi/key-west-10238/video-request22-mm-000191-a-kkyle-david-nybakken-167937/
https://www.muckrock.com/foi/crawford-county-8589/video-request-2022cf000031check-matthew-w-167673/
https://www.muckrock.com/foi/belle-isle-10257/video-request2023-cf-011619-a-okarla-matavazquez-171248/#
https://www.muckrock.com/foi/key-west-10238/video-request22-cf-000046-a-kalbert-alty-167725/
https://www.muckrock.com/foi/key-west-10238/video-request22-cf-000018-a-kmatthew-james-roberts-167723/
https://www.muckrock.com/foi/key-west-10238/video-request-168471/

**Comment by mitchelljkotler** [comment]
This seems to happen only for awaiting acknowledgement / awaiting response requests which are being snail mailed or faxed
