### ISSUE TITLE
Logged out Mailchimp widget not working, needs to take subscribers properly

### ISSUE THREAD

**Issue by eyeseast** [MuckRock/muckrock#1920]
For logged out users, there's  a widget that pops up when they scroll down the page. I think it's some mailchimp — we might need to generate a new widget in Mailchimp if that's the case which @kellykauffman can do, but wanted to see if @mitchelljkotler had ideas about what might be broken first.

![Image](https://github.com/user-attachments/assets/e5c3c3f5-19cf-4452-b016-3f12b5e02935)

**Comment by eyeseast** [comment]
Go to any news URL (such as https://www.muckrock.com/news/archives/2024/oct/08/a-new-documentcloud-is-coming-try-it-now/) and scroll down. The widget should slide in from the right.

**Comment by mitchelljkotler** [comment]
It looks like MailChimp changed the way this works.  It is harder to only show to logged out users and control which page it shows up on.  Also, Firefox seems to block it by default.  We already have a built in newsletter sign up.  I would propose just removing this.
