### ISSUE TITLE
Proxy Tasks

### ISSUE THREAD

**Issue by blipblitz** [MuckRock/muckrock#341]
Could we have a separate setting to signify that a request needs to be resubmitted using a proxy?

**Comment by morisy** [comment]
This is still relevant, and in addition to having a proxy task it would be super helpful to have a list on the site (assuming one doesn’t already exist and I’m just not aware of it) of all the proxies, as well as any specific rules that apply to submitting a request through a proxy in a given state. - C

**Comment by mitchelljkotler** [comment]
List of all proxies: https://www.muckrock.com/admin/auth/user/?profile__acct_type__exact=proxy

**Comment by mitchelljkotler** [comment]
How do we feel about holding off on this, since soon we will have shell companies to get around this?
