### ISSUE TITLE
Include last attached communication from the agency on Appeal Snail Mail tasks

### ISSUE THREAD

**Issue by blipblitz** [MuckRock/muckrock#399]
When a user sends an appeal, usually the last attached communication from the agency is the rejection letter, which needs to be included, so it may as well be added to the snail mail task, allowing us to access/print it more easily.

**Comment by morisy** [comment]
"This would be nice to have but we won’t die without it. As long as people know that they need to include all correspondence in an appeal." - C

**Comment by morisy** [comment]
Appeals should broadly be remodeled. Need to start a great FOIA remodel milestone to stuff this stuff in.
