### ISSUE TITLE
Removing MuckRock email addresses from Request email fields

### ISSUE THREAD

**Issue by blipblitz** [MuckRock/muckrock#446]
I just spent a stupid amount of time cleaning up requests that had ended up with their own MuckRock email addresses in the Email field for the request, meaning that there were huge email chains and weird message feedback loops that needed to be sorted through. Is there a way to find all of the times our own BlahBlah-NumbersNumbersNumbers@requests.muckrock.com are listed in the Email field of the Request backend page and, relatedly, finding instances where that is the only email address listed?

**Comment by morisy** [comment]
Another example: https://www.muckrock.com/admin/foia/foiarequest/18540/change/ Interesting case because the agency CC'd multiple MuckRock requests in one email.

**Comment by morisy** [comment]
This one had the issue where the email was included three times, once as to and twice as CC. I cleaned it up: https://www.muckrock.com/admin/foia/foiarequest/40402/change/
