### ISSUE TITLE
Automatically resolving tasks made irrelevant by user action.

### ISSUE THREAD

**Issue by blipblitz** [MuckRock/muckrock#450]
As we scale up, it may be good to consider a way to automatically resolve response tasks that are irrelevant, because the user is on top of the request already. Right now a response task's "More Info" updates to include communications that were exchanged after the one being dealt with in that task. Maybe there's a clean way there to determine whether a response task really needs to exist at all.

**Comment by morisy** [comment]
I'm pretty sure this was implemented.
