### ISSUE TITLE
Filter for updated requests in "my requests" list

### ISSUE THREAD

**Issue by shawnmusgrave** [MuckRock/muckrock#482]
When I clicked the "Click to see all" button in the Updates sidebar section, I expected that I would see a list of all my requests with an open update. Instead, I'm taken to 

https://www.muckrock.com/foi/mylist/

There's no way to filter for requests with an unread update.

**Comment by morisy** [comment]
So I think this goes back to the move from read/unread to notification system. There's improvements that can be made to how we communicate updates, but so far almost no negative feedback on it beyond this bug in over two years. Will continue to work on improving experience in other ways.
