### ISSUE TITLE
Allow organization owner to buy more requests

### ISSUE THREAD

**Issue by morisy** [MuckRock/muckrock#499]
I think the most straight forward way for orgs to get topped off is for the org admin to just use the "Buy requests" button on the backend and the requests are just added to the orgs account, not their own, but open to alternatives.

One open question would be if they buy additional requests, do those roll over like pro account additional requests do? I would say no because that adds a layer of complexity, but don't feel super sure about that one.

**Comment by morisy** [comment]
Just rebumping this. I'm fine with waiting on it, because there is only one organization taking advantage of it now, but right now the process is:

a) They manually email me they need more requests this month.
b) I manually add the requests on the backend. 
c) I manually charge them for the requests.
d) I manually generate the receipt.
e) I cross my fingers and hope they use all the extra requests they bought before they expire at the end of the month.

Not a huge deal right now since again, it's just one org and it only comes up every three months, but it's bound to cause problems.

**Comment by mitchelljkotler** [comment]
This was done with the squarelet refactoring
