### ISSUE TITLE
Allow pages to be individually de-indexed by admins

### ISSUE THREAD

**Issue by morisy** [MuckRock/muckrock#501]
Occasionally we'll have public information we don't necessarily want public-public, like addresses, phone numbers, etc.

A checkbox that would, when checked, put a do not crawl tag in the header:

<meta name="robots" content="noindex, follow">

We don't want these pages in the normal do not crawl index because than those looking for sensitive information would have it all in one place.

I'm not totally sold on this, so welcome other opinions and problems with it.

**Comment by morisy** [comment]
Related discussion: http://michaeljaylissner.com/posts/2012/01/16/respecting-privacy-while-providing-hundreds-of-thousands-of-public-documents/

**Comment by morisy** [comment]
This would solve a variety of occasional headaches, but won't resolve underlying policy questions. Related discussion of freedom of speech vs. freedom of reach: http://www.niemanlab.org/2019/02/while-youtube-and-facebook-fumble-pinterest-is-reducing-health-misinformation-in-ways-that-actually-make-sense/

**Comment by mitchelljkotler** [comment]
This was implemented 2019-07-15 - individual FOIA Requests may be de-indexed
