### ISSUE TITLE
Adding a new tag

### ISSUE THREAD

**Issue by shawnmusgrave** [MuckRock/muckrock#564]
On this request:

https://www.muckrock.com/foi/new-york-city-17/nypd-annual-firearms-discharge-reports-2007-to-2014-20819/

I added one tag: police involved shooting

![screen shot 2015-08-25 at 3 32 07 pm](https://cloud.githubusercontent.com/assets/7838930/9477142/a8c7443a-4b3e-11e5-809c-2453087a8c1e.png)

Then realized I wanted to add a second tag: use of force
When I clicked in, the tag field had put quotes around my first tag: 

![screen shot 2015-08-25 at 3 32 29 pm](https://cloud.githubusercontent.com/assets/7838930/9477156/b8f3c9be-4b3e-11e5-8e1a-19fd2797727f.png)

The current instructions don't indicate how to properly add a second tag. When I put the second tag outside the quotes:

![screen shot 2015-08-25 at 3 32 43 pm](https://cloud.githubusercontent.com/assets/7838930/9477171/d11060fc-4b3e-11e5-99e2-61913d09b983.png)

... the first one was now in quotes: 
![screen shot 2015-08-25 at 3 32 57 pm](https://cloud.githubusercontent.com/assets/7838930/9477172/d1115fa2-4b3e-11e5-8e5f-4177ddc99ed1.png)

Only when I removed the quotes around both tags in the field did they display appropriately:
![screen shot 2015-08-25 at 3 33 18 pm](https://cloud.githubusercontent.com/assets/7838930/9477173/d1154248-4b3e-11e5-8354-c9e37d05a386.png)

But now we also have a "police involved shooting" tag.

**Comment by morisy** [comment]
This seems to be working now. If not, reopen with examples.
