### ISSUE TITLE
When new agency tasks rejected, moved to different agency, communication direct objects don't follow

### ISSUE THREAD

**Issue by morisy** [MuckRock/muckrock#624]
Pretty edge case but something to be aware of: A bad "Federal Bureau of Investigations" was set up by someone. I moved the requests over to the new agency using the Reject & Move tool, but the activities are still linked to the old one. 

https://www.muckrock.com/admin/agency/agency/5977/delete/

**Comment by mitchelljkotler** [comment]
What activities?

**Comment by morisy** [comment]
The notifications that are stored on the backend to let users know when a request has been updated. There were (maybe are) some edge cases where it goes out to a bad agency, the agency responds, the bad agency is deleted, and the user wouldn't have that notification anymore because when you delete bad agencies the notifications got deleted with them because they were dependent on them.

Probably safe to close this one because agencies just shouldn't be deleted.
