### ISSUE TITLE
Suggestion for Multi-Request tasks.

### ISSUE THREAD

**Issue by blipblitz** [MuckRock/muckrock#651]
Helpful information to include:
- Text language of the request.

Helpful feature:
- Check boxes to remove inappropriate agencies coupled with the Resolve button acting as a Submit button.

**Comment by mitchelljkotler** [comment]
So when we return requests, we have no way of telling if they were monthly requests or bought requests - should we just always return them as bought requests?

**Comment by morisy** [comment]
I think we should track that in the multirequest object and return as appropriate.
