### ISSUE TITLE
Merge one agency into another

### ISSUE THREAD

**Issue by allanlasser** [MuckRock/muckrock#693]
Seems like a pretty frequent task and it would automate well.

Just sketching it out, calling `agency_a.merge(agency_b)` should change all requests that reference `agency_a` to instead reference `agency_b`. After that, `agency_a` should be deleted.

Although, it's definitely more complicated than that. Should there be any restrictions on `agency_b`, like matching names or jurisdictions? Should the FOIAs be resubmitted after getting moved over?

**Comment by morisy** [comment]
Possibly also including ability to merge jurisdictions, though that is *extremely* rare, maybe once a year though I think there's a bunch of dupe North Carolina jurisdictions I've been putting off.

**Comment by mitchelljkotler** [comment]
This was done 2019-02-27
