### ISSUE TITLE
Quick download of all communications for a given request — including *original* emails

### ISSUE THREAD

**Issue by shawnmusgrave** [MuckRock/muckrock#72]
Every so often a requester pursuing litigation or a serious appeal asks for all original emails, incl. metadata, for a request or host of requests. There ought to be an easy "Download all communications" button that exports a .zip folder of all correspondence for a given request. 

NOTE: this might mean bringing Faxaway confirmation messages onto the request page — users haranguing laggard agencies for non-response or FOIA violations will want confirmations of receipt. Email opening/receipt confirmations, too?

**Comment by mitchelljkotler** [comment]
No raw emails, txt file for each comm, all files, only on own requests, staff on any request
