### ISSUE TITLE
Possible email verification bug

### ISSUE THREAD

**Issue by morisy** [MuckRock/muckrock#855]
User reported being unable to verify account. I haven't tried to duplicate yet, but wouldn't be surprised if it's a bug. Very rarely run into a user with a properly verified email.

---------- Forwarded message ----------
From: Steinberg, Becky RSteinberg@vocativ.com
Date: Tue, Mar 22, 2016 at 4:53 PM
Subject: Re: Verify Your MuckRock Email
To: "info@muckrock.com" info@muckrock.com

Hi,
I am trying to verify my account but every time I copy the link to the URL bar, it tells me the confirmation key is invalid.  Can you please help?
Thank you,
Becky

On 3/22/16, 4:45 PM, "info=muckrock.com@requests.muckrock.com on behalf of info@muckrock.com" <info=muckrock.com@requests.muckrock.com on behalf of info@muckrock.com> wrote:

> Hi Vocativ,
> 
> This message is to verify the email associated with your account on MuckRock.com.
> Follow this link to complete the verification process: https://www.muckrock.com/accounts/settings/verify_email/?key=G00RLYTLL4N6Z1GFG6ERK915&uuid-login=f697c6c2-b733-4d23-a3a8-9a4ee27ea963
> 
> If you have any questions, send an email to info@muckrock.com and we'll help you out.
> 
> Thank you!
> MuckRock Staff

**Comment by mitchelljkotler** [comment]
I believe this is all resolved with squarelet now
