### ISSUE TITLE
Create "Agency" User Account Type

### ISSUE THREAD

**Issue by morisy** [MuckRock/muckrock#863]
Allow agencies to have user accounts. Typically these accounts would just be able to update certain aspects of their requests from a request updating page.

These accounts may not have exposed all the normal features of regular MuckRock accounts:
- They might not have normal usernames.
- They might not have user-settable passwords, instead logging in with one-time login tokens.
- They cannot file requests.
- They might have minimal navigation tools to get to other parts of the site.
- Their primary interaction will likely be click a link from an email, and then respond to just that request.

**Comment by mitchelljkotler** [comment]
this was done a while ago
