### ISSUE TITLE
Organization Registration/Management Tweaks

### ISSUE THREAD

**Issue by morisy** [MuckRock/muckrock#872]
Juggling a bunch of things this morning, but wanted to get something up so we'd talk about it at some point:
- I think I was wrong in having org creator not be a member by default. I think it's about even how often org creators are also members, so that the best way would be to tweak it so that: Org creators are members; the next page they see after registration is the member management page, with a little notification that they're a member by default, but if they're not going to file they can remove themselves and add another member.
- Having to "add seats" before you can add members is a really awkward UX. You should just be able to add names, see the impact on your bill, and confirm; all on one page.
- This goes beyond a design tweak, but we need a way to invite/ask to join orgs. Lower priority than the other two.

I'll try to separate these out to three separate issues, or we can do that once we've talked through them.

**Comment by morisy** [comment]
The top one (Org creators should be members of their org by default) keeps coming up, so bumping it to high.

**Comment by mitchelljkotler** [comment]
This is a squarelet issue now, with 1 and 3 being resolved and 2 still being an issue
