### ISSUE TITLE
Better ToMail Automation

### ISSUE THREAD

**Issue by morisy** [MuckRock/muckrock#896]
Something I've been noodling on and will continue to noodle on for a bit, but feel like To Mail processes eventually must scale. Right now, we're spending very little on it so it seems pretty manageable, so just using this issue to track links, ideas, possible solutions.

https://twitter.com/panic/status/697888676546637824/video/1
https://panic.com/blog/firewatch-one-month-later/

**Comment by mitchelljkotler** [comment]
@morisy I was calling for lob as early as 2016....

**Comment by morisy** [comment]
Still think we should have built robots.
