### ISSUE TITLE
Way to rotate documents on site

### ISSUE THREAD

**Issue by morisy** [MuckRock/muckrock#90]
There should be a way to rotate documents. Often times they're posted sideways, which is super frustrating for users and generating the page as the canonical place to view documents.

Ex: https://www.muckrock.com/foi/united-states-of-america-10/guantanamo-bay-vip-visitors-6005/#1363028-responsive-documents

There's a good chance we want to open this to users, too, but I think at first making it admin only but on the front end makes sense and then rolling out to users later.

**Comment by mitchelljkotler** [comment]
https://github.com/pmaupin/pdfrw
https://github.com/mstamy2/PyPDF2
