### ISSUE TITLE
"In Litigation" Status

### ISSUE THREAD

**Issue by morisy** [MuckRock/muckrock#979]
Can we added a "In Litigation" status type? Similar to appeal, users want to be able to just have a request as marked "In Litigation".

The only way that a request should be able to get this status for now is for a user to manually change it to litigation; it should disable auto follow ups.

**Comment by Asparagirl** [comment]
🎉 Huzzah! 🎉

**Comment by morisy** [comment]
@Asparagirl Still a few bugs to quash to get it live on the site but almost!
